
services:
  reverse-proxy:
    image: traefik:v2.10
    command:
      - "--providers.docker"
      - "--providers.file.directory=/configuration/"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
    environment:
      - SSL_CERT_CRT=${SSL_CERT_CRT}
      - SSL_CERT_KEY=${SSL_CERT_KEY}
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yaml:/configuration/traefik.yml
  backend:
    image: backend
    build:
      context: ./
    environment:
      - USE_TRAEFIK=1
    labels:
      - "traefik.http.routers.backend.priority=1001"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.rule=PathPrefix(`/api/v1`)"
      - "traefik.http.services.backend.loadbalancer.server.port=8081"
      - "traefik.http.routers.backend.middlewares=backend-compress,backend-ratelimit,backend-strip"
      - "traefik.http.middlewares.backend-ratelimit.ratelimit.average=50"
      - "traefik.http.middlewares.backend-ratelimit.ratelimit.burst=25"
      - "traefik.http.middlewares.backend-ratelimit.ratelimit.period=1"
      - "traefik.http.middlewares.backend-compress.compress=true"
      - "traefik.http.middlewares.backend-strip.replacepathregex.regex=^/api/v1/?(.*)"
      - "traefik.http.middlewares.backend-strip.replacepathregex.replacement=/$1"
      - "traefik.http.routers.backend-docs.rule=PathPrefix(`/api/v1/docs`)"
      - "traefik.http.routers.backend-docs.tls=true"
      - "traefik.http.routers.backend-docs.priority=1002"
      - "traefik.http.routers.backend-docs.service=backend"
      - "traefik.http.routers.backend-docs.middlewares=backend-compress,backend-ratelimit"
    expose:
      - 8081
