version: '3.9'

volumes:
  eucalc:

services:
  reverse-proxy:
    image: traefik:v2.10
    command:
      - "--providers.docker"
      - "--providers.file.directory=/configuration/"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
    labels:
      - "traefik.http.middlewares.secureHeaders.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.secureHeaders.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.redirect-to.redirectregex.regex=^https?:\\/\\/([^\\/]+)\\/?$$"
      - "traefik.http.middlewares.redirect-to.redirectregex.replacement=https://$$1/en-US/"
      - "traefik.http.middlewares.redirect-to.redirectregex.permanent=true"
    environment:
      - SSL_CERT_CRT=${SSL_CERT_CRT}
      - SSL_CERT_KEY=${SSL_CERT_KEY}
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yaml:/configuration/traefik.yml
      - /etc/ssl:/etc/ssl
  knime2python:
    image: knime2python
    build:
      context: ./knime2python
    labels:
      - "traefik.http.routers.knime2python.priority=1001"
      - "traefik.http.routers.knime2python.tls=true"
      - "traefik.http.routers.knime2python.rule=PathPrefix(`/api/v1.0/`)||PathPrefix(`/admin/`)||PathPrefix(`/static/admin/`)||PathPrefix(`/health`)"
      - "traefik.http.services.knime2python.loadbalancer.server.port=5000"
      - "traefik.http.routers.knime2python.middlewares=knime2python-compress,knime2python-ratelimit,secureHeaders@docker"
      - "traefik.http.middlewares.knime2python-ratelimit.ratelimit.average=50"
      - "traefik.http.middlewares.knime2python-ratelimit.ratelimit.burst=25"
      - "traefik.http.middlewares.knime2python-ratelimit.ratelimit.period=1"
      - "traefik.http.middlewares.knime2python-compress.compress=true"
    expose:
      - 5000
    volumes:
      - eucalc:/app/database
      - ./knime2python/config:/eucalc/config
      - ./knime2python/_interactions:/eucalc/_interactions
  transition-pathway-explorer:
    image: transition-pathway-explorer
    build: ./transition-pathway-explorer
    expose:
      - 80
    environment:
      - SERVER_HOST=http://knime2python:8000
    labels:
      - "traefik.http.routers.transition-pathway-explorer.tls=true"
      - "traefik.http.routers.transition-pathway-explorer.rule=PathPrefix(`/`)"
      - "traefik.http.services.transition-pathway-explorer.loadbalancer.server.port=80"
      - "traefik.http.routers.transition-pathway-explorer.middlewares=secureHeaders@docker,redirect-to"
      - "traefik.http.routers.transition-pathway-explorer.entrypoints=web,websecure"
