version: "3"
services:
  api:
    image: climact/eucalc:v4.2_no_emp
    command:
      - "-w 1"
    depends_on:
      - db
    network_mode: "host"  # Changed by tobi
  db:
    image: mysql:5.7
    command:
      - --max_allowed_packet=32505856
      - --port=3307  # Changed by tobi
    restart: always
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d/:ro
    environment:
      MYSQL_ROOT_PASSWORD: 7VupwgCxBQVZ
      MYSQL_DATABASE: eucalc
    network_mode: "host"  # Changed by tobi
