import type { Lever } from 'src/utils/leversData';

export const levers: Lever[] = [
  {
    code: 'lever_pkm',
    title: {
      enUS: 'Passenger distance',
      frFR: 'Distance de voyage',
      deDE: 'Fahrtdistanz',
    },
    group: {
      enUS: 'Travel',
      frFR: 'Voyages',
      deDE: 'Reisen',
    },
    headline: {
      enUS: 'Key behaviours',
      frFR: 'Comportements clés',
      deDE: 'Schlüsselverhalten',
    },
    range: [1, 2, 3, 4],
    type: 'num',
    chartType: 'Line',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_passenger_modal-share',
    title: {
      enUS: 'Mode of transport',
      frFR: 'Mode de transport',
      deDE: 'Verkehrsmittel',
    },
    group: {
      enUS: 'Travel',
      frFR: 'Voyages',
      deDE: 'Reisen',
    },
    headline: {
      enUS: 'Key behaviours',
      frFR: 'Comportements clés',
      deDE: 'Schlüsselverhalten',
    },
    range: [1, 2, 3, 4],
    type: 'num',
    chartType: 'StackedArea',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_passenger_occupancy',
    title: {
      enUS: 'Occupancy',
      frFR: "Taux d'occupation",
      deDE: 'Auslastung',
    },
    group: {
      enUS: 'Travel',
      frFR: 'Voyages',
      deDE: 'Reisen',
    },
    headline: {
      enUS: 'Key behaviours',
      frFR: 'Comportements clés',
      deDE: 'Schlüsselverhalten',
    },
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_passenger_utilization-rate',
    title: {
      enUS: 'Utilisation rate',
      frFR: "Taux d'utilisation",
      deDE: 'Nutzungsrate',
    },
    group: {
      enUS: 'Travel',
      frFR: 'Voyages',
      deDE: 'Reisen',
    },
    headline: {
      enUS: 'Key behaviours',
      frFR: 'Comportements clés',
      deDE: 'Schlüsselverhalten',
    },
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_floor-intensity',
    title: {
      enUS: 'Living space per person',
      frFR: 'Surface habitable par personne',
      deDE: 'Wohnfläche pro Person',
    },
    group: {
      enUS: 'Homes',
      frFR: 'Logements',
      deDE: 'Wohnungen',
    },
    headline: {
      enUS: 'Key behaviours',
      frFR: 'Comportements clés',
      deDE: 'Schlüsselverhalten',
    },
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_floor-area-fraction',
    title: {
      enUS: 'Percentage of cooled living space',
      frFR: 'Espace climatisé',
      deDE: 'Klimatisierte Wohnfläche',
    },
    group: {
      enUS: 'Homes',
      frFR: 'Logements',
      deDE: 'Wohnungen',
    },
    headline: {
      enUS: 'Key behaviours',
      frFR: 'Comportements clés',
      deDE: 'Schlüsselverhalten',
    },
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_heatcool-behaviour',
    title: {
      enUS: 'Heating temperature',
      frFR: 'Température de chauffage',
      deDE: 'Heiztemperatur',
    },
    group: {
      enUS: 'Homes',
      frFR: 'Logements',
      deDE: 'Wohnungen',
    },
    headline: {
      enUS: 'Key behaviours',
      frFR: 'Comportements clés',
      deDE: 'Schlüsselverhalten',
    },
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },

  {
    code: 'lever_kcal-req',
    title: {
      enUS: 'Calories consumed',
      frFR: 'Calories consommées',
      deDE: 'Kalorienverbrauch',
    },
    group: {
      enUS: 'Diet',
      frFR: 'Alimentation',
      deDE: 'Ernährung',
    },
    headline: {
      enUS: 'Key behaviours',
      frFR: 'Comportements clés',
      deDE: 'Schlüsselverhalten',
    },
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_diet',
    title: {
      enUS: 'Type of diet',
      frFR: "Type d'alimentation",
      deDE: 'Ernährungstyp',
    },
    group: {
      enUS: 'Diet',
      frFR: 'Alimentation',
      deDE: 'Ernährung',
    },
    headline: {
      enUS: 'Key behaviours',
      frFR: 'Comportements clés',
      deDE: 'Schlüsselverhalten',
    },
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_paperpack',
    title: {
      enUS: 'Use of paper and packaging',
      frFR: 'Papier et emballage',
      deDE: 'Papier und Verpackung',
    },
    group: {
      enUS: 'Consumption',
      frFR: 'Consommation',
      deDE: 'Konsum',
    },
    headline: {
      enUS: 'Key behaviours',
      frFR: 'Comportements clés',
      deDE: 'Schlüsselverhalten',
    },
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_product-substitution-rate',
    title: {
      enUS: 'Appliance retirement timing',
      frFR: 'Durée de remplacement',
      deDE: 'Geräte-Austauschzeitpunkt',
    },
    group: {
      enUS: 'Consumption',
      frFR: 'Consommation',
      deDE: 'Konsum',
    },
    headline: {
      enUS: 'Key behaviours',
      frFR: 'Comportements clés',
      deDE: 'Schlüsselverhalten',
    },
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_fwaste',
    title: {
      enUS: 'Food waste',
      frFR: 'Gaspillage alimentaire',
      deDE: 'Lebensmittelverschwendung',
    },
    group: {
      enUS: 'Consumption',
      frFR: 'Consommation',
      deDE: 'Konsum',
    },
    headline: {
      enUS: 'Key behaviours',
      frFR: 'Comportements clés',
      deDE: 'Schlüsselverhalten',
    },
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_freight_tkm',
    title: {
      enUS: 'Freight distance',
      frFR: 'Distance de fret',
      deDE: 'Frachtstrecke',
    },
    group: {
      enUS: '',
      frFR: '',
      deDE: '',
    },
    headline: {
      enUS: '',
      frFR: '',
      deDE: '',
    },
    popupText: {
      enUS: 'Freight tonne-kilometers (tkm) represent the total transport work done to move freight. It is calculated by multiplying the weight of the freight (in tonnes) by the distance it is transported (in kilometers). Reducing freight tkm can be achieved through strategies such as optimizing logistics, improving supply chain efficiency, and promoting local sourcing to minimize transportation distances.',
      frFR: "Les tonnes-kilomètres de fret (tkm) représentent le travail de transport total effectué. Elles sont calculées en multipliant le poids du fret (en tonnes) par la distance de transport (en km). La réduction des tkm peut être atteinte par l'optimisation logistique, l'efficacité de la chaîne d'approvisionnement et l'approvisionnement local.",
      deDE: 'Fracht-Tonnenkilometer (tkm) stellen die gesamte Transportleistung dar. Sie werden berechnet durch Multiplikation des Frachtengewichts (in Tonnen) mit der Transportentfernung (in km). Die Reduktion von Fracht-tkm kann durch Logistikoptimierung, Lieferketteneffizienz und lokale Beschaffung erreicht werden.',
    },
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_passenger_veh-efficiency_new',
    title: {
      enUS: 'Passenger efficiency',
      frFR: 'Efficacité des véhicules',
      deDE: 'Fahrzeugeffizienz',
    },
    group: {
      enUS: 'Transport',
      frFR: 'Transport',
      deDE: 'Transport',
    },
    headline: {
      enUS: 'Technology and fuels',
      frFR: 'Technologie et combustibles',
      deDE: 'Technik und Brennstoffe',
    },
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_passenger_technology-share_new',
    title: {
      enUS: 'New passenger tech',
      frFR: 'Nouvelle technologie',
      deDE: 'Neue Fahrzeugtechnik',
    },
    group: {
      enUS: 'Transport',
      frFR: 'Transport',
      deDE: 'Transport',
    },
    headline: {
      enUS: 'Technology and fuels',
      frFR: 'Technologie et combustibles',
      deDE: 'Technik und Brennstoffe',
    },
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_freight_vehicle-efficiency_new',
    title: {
      enUS: 'Freight efficiency',
      frFR: 'Efficacité du fret',
      deDE: 'Lastereffizienz',
    },
    group: {
      enUS: '',
      frFR: '',
      deDE: '',
    },
    headline: {
      enUS: '',
      frFR: '',
      deDE: '',
    },
    popupText: {
      enUS: 'Freight vehicle efficiency refers to the effectiveness of freight vehicles in utilizing energy to transport goods. It is typically measured in terms of fuel consumption per ton-mile or ton-kilometer. Improving freight vehicle efficiency can involve adopting advanced technologies, optimizing vehicle design, and implementing better maintenance practices to reduce fuel consumption and emissions.',
      frFR: "L'efficacité des véhicules de fret se rapporte à l'efficacité de la consommation de carburant par tonne-km. L'amélioration peut être obtenue par l'adoption de technologies avancées, l'optimisation de la conception des véhicules et de meilleures pratiques d'entretien.",
      deDE: 'Die Effizienz von Lastwagen bezieht sich auf die Effektivität bei der Umwandlung von Energie in Transportleistung. Sie wird üblicherweise in Treibstoffverbrauch pro Tonne-Kilometer gemessen. Die Verbesserung kann durch fortschrittliche Technologien, Fahrzeugoptimierung und bessere Wartung erreicht werden.',
    },
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_freight_technology-share_new',
    title: {
      enUS: 'Freight technology',
      frFR: 'Technologie du fret',
      deDE: 'Lastertechnik',
    },
    group: {
      enUS: '',
      frFR: '',
      deDE: '',
    },
    headline: {
      enUS: '',
      frFR: '',
      deDE: '',
    },
    popupText: {
      enUS: 'Freight technology share refers to the proportion of freight transport that utilizes advanced or alternative technologies, such as electric or hydrogen-powered vehicles, compared to traditional fossil fuel-powered vehicles. Increasing the share of advanced technologies in freight transport can help reduce greenhouse gas emissions and improve overall energy efficiency in the logistics sector.',
      frFR: "La part technologique du fret se rapporte à la proportion de transport de fret utilisant des technologies avancées ou alternatives (véhicules électriques ou à hydrogène) par rapport aux véhicules traditionnels. L'augmentation peut aider à réduire les émissions de gaz à effet de serre.",
      deDE: 'Der Technologieanteil bei Frachttransport bezieht sich auf den Anteil von Fahrzeugen mit fortschrittlichen oder alternativen Technologien (z.B. elektrisch oder wasserstoffbetrieben) im Vergleich zu konventionellen Fahrzeugen. Eine Steigerung kann zur Reduktion von Treibhausgasemissionen beitragen.',
    },
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_freight_modal-share',
    title: {
      enUS: 'Freight mode',
      frFR: 'Mode de fret',
      deDE: 'Frachtverkehrsmittel',
    },
    group: {
      enUS: 'Transport',
      frFR: 'Transport',
      deDE: 'Transport',
    },
    headline: {
      enUS: 'Technology and fuels',
      frFR: 'Technologie et combustibles',
      deDE: 'Technik und Brennstoffe',
    },
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_freight_utilization-rate',
    title: {
      enUS: 'Freight utilization rate',
      frFR: "Taux d'utilisation du fret",
      deDE: 'Frachtutzungsrate',
    },
    group: {
      enUS: 'Transport',
      frFR: 'Transport',
      deDE: 'Transport',
    },
    headline: {
      enUS: 'Technology and fuels',
      frFR: 'Technologie et combustibles',
      deDE: 'Technik und Brennstoffe',
    },
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_fuel-mix',
    title: {
      enUS: 'Fuel mix',
      frFR: 'Mix de carburants',
      deDE: 'Brennstoffmix',
    },
    group: {
      enUS: 'Transport',
      frFR: 'Transport',
      deDE: 'Transport',
    },
    headline: {
      enUS: 'Technology and fuels',
      frFR: 'Technologie et combustibles',
      deDE: 'Technik und Brennstoffe',
    },
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_building-renovation-rate',
    title: {
      enUS: 'Building envelope',
      frFR: 'Enveloppe bâtiment',
      deDE: 'Gebäudehülle',
    },
    group: {
      enUS: 'Buildings',
      frFR: 'Bâtiments',
      deDE: 'Gebäude',
    },
    headline: {
      enUS: 'Technology and fuels',
      frFR: 'Technologie et combustibles',
      deDE: 'Technik und Brennstoffe',
    },
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_services-floor-area',
    title: {
      enUS: 'Services floor area',
      frFR: 'Surface au sol des services',
      deDE: 'Fläche der Dienstleistungen',
    },
    group: {
      enUS: 'Buildings',
      frFR: 'Bâtiments',
      deDE: 'Gebäude',
    },
    headline: {
      enUS: 'Technology and fuels',
      frFR: 'Technologie et combustibles',
      deDE: 'Technik und Brennstoffe',
    },
    range: [1, 2, 3, 4], // Adjust min/max as needed
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
    popupText: {
      // Optional: shown in lever details popup
      enUS: 'Explanation text',
      frFR: 'Surface au sol utilisée pour les services',
      deDE: 'Erklärungstext',
    },
  },
  {
    code: 'lever_district-heating-share',
    title: {
      enUS: 'District heating share',
      frFR: 'Part chauffage urbain',
      deDE: 'Fernwärmeanteil',
    },
    group: {
      enUS: 'Buildings',
      frFR: 'Bâtiments',
      deDE: 'Gebäude',
    },
    headline: {
      enUS: 'Technology and fuels',
      frFR: 'Technologie et combustibles',
      deDE: 'Technik und Brennstoffe',
    },
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_heating-technology-fuel',
    title: {
      enUS: 'Technology and fuel share',
      frFR: 'Technologie chauffage',
      deDE: 'Heiztech & Brennstoff',
    },
    group: {
      enUS: 'Buildings',
      frFR: 'Bâtiments',
      deDE: 'Gebäude',
    },
    headline: {
      enUS: 'Technology and fuels',
      frFR: 'Technologie et combustibles',
      deDE: 'Technik und Brennstoffe',
    },
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_heating-efficiency',
    title: {
      enUS: 'Heating tech efficiency',
      frFR: 'Efficacité chauffage',
      deDE: 'Heizeffizienz',
    },
    group: {
      enUS: 'Buildings',
      frFR: 'Bâtiments',
      deDE: 'Gebäude',
    },
    headline: {
      enUS: 'Technology and fuels',
      frFR: 'Technologie et combustibles',
      deDE: 'Technik und Brennstoffe',
    },
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_material-efficiency',
    title: {
      enUS: 'Material efficiency',
      frFR: 'Efficacité matériaux',
      deDE: 'Materialeffizienz',
    },
    group: {
      enUS: 'Manufacturing',
      frFR: 'Fabrication',
      deDE: 'Fertigung',
    },
    headline: {
      enUS: 'Technology and fuels',
      frFR: 'Technologie et combustibles',
      deDE: 'Technik und Brennstoffe',
    },
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_material-switch',
    title: {
      enUS: 'Material switch',
      frFR: 'Changement matériau',
      deDE: 'Materialwechsel',
    },
    group: {
      enUS: 'Manufacturing',
      frFR: 'Fabrication',
      deDE: 'Fertigung',
    },
    headline: {
      enUS: 'Technology and fuels',
      frFR: 'Technologie et combustibles',
      deDE: 'Technik und Brennstoffe',
    },
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_technology-share',
    title: {
      enUS: 'Technology efficiency',
      frFR: 'Efficacité technologie',
      deDE: 'Technologieeffizienz',
    },
    group: {
      enUS: 'Manufacturing',
      frFR: 'Fabrication',
      deDE: 'Fertigung',
    },
    headline: {
      enUS: 'Technology and fuels',
      frFR: 'Technologie et combustibles',
      deDE: 'Technik und Brennstoffe',
    },
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_technology-development',
    title: {
      enUS: 'Energy efficiency',
      frFR: 'Efficacité énergétique',
      deDE: 'Energieeffizienz',
    },
    group: {
      enUS: 'Manufacturing',
      frFR: 'Fabrication',
      deDE: 'Fertigung',
    },
    headline: {
      enUS: 'Technology and fuels',
      frFR: 'Technologie et combustibles',
      deDE: 'Technik und Brennstoffe',
    },
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_energy-carrier-mix',
    title: {
      enUS: 'Fuel mix',
      frFR: 'Mix combustible',
      deDE: 'Brennstoffmix',
    },
    group: {
      enUS: 'Manufacturing',
      frFR: 'Fabrication',
      deDE: 'Fertigung',
    },
    headline: {
      enUS: 'Technology and fuels',
      frFR: 'Technologie et combustibles',
      deDE: 'Technik und Brennstoffe',
    },
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_cc',
    title: {
      enUS: 'Carbon Capture in manufacturing',
      frFR: 'Capture carbone',
      deDE: 'Kohlenstoffabscheidung',
    },
    group: {
      enUS: 'Manufacturing',
      frFR: 'Fabrication',
      deDE: 'Fertigung',
    },
    headline: {
      enUS: 'Technology and fuels',
      frFR: 'Technologie et combustibles',
      deDE: 'Technik und Brennstoffe',
    },
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_ccus',
    title: {
      enUS: 'Carbon Capture to fuel',
      frFR: 'Carbone en combustible',
      deDE: 'Kohlenstoff in Brennstoff',
    },
    group: {
      enUS: 'Manufacturing',
      frFR: 'Fabrication',
      deDE: 'Fertigung',
    },
    headline: {
      enUS: 'Technology and fuels',
      frFR: 'Technologie et combustibles',
      deDE: 'Technik und Brennstoffe',
    },
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_climate-smart-crop',
    title: {
      enUS: 'Climate smart crop production',
      frFR: 'Agriculture climat-intelligente',
      deDE: 'Klimabewusste Landwirtschaft',
    },
    group: {
      enUS: 'Land and food',
      frFR: 'Terre et alimentation',
      deDE: 'Land und Ernährung',
    },
    headline: {
      enUS: 'Resources and land use',
      frFR: 'Ressources et utilisation des terres',
      deDE: 'Ressourcen und Landnutzung',
    },
    range: [1, 2, 3, 4],
    type: 'char',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_climate-smart-livestock',
    title: {
      enUS: 'Climate smart livestock',
      frFR: 'Élevage climat-intelligent',
      deDE: 'Klimabewusste Viehzucht',
    },
    group: {
      enUS: 'Land and food',
      frFR: 'Terre et alimentation',
      deDE: 'Land und Ernährung',
    },
    headline: {
      enUS: 'Resources and land use',
      frFR: 'Ressources et utilisation des terres',
      deDE: 'Ressourcen und Landnutzung',
    },
    range: [1, 2, 3, 4],
    type: 'char',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_bioenergy-capacity',
    title: {
      enUS: 'Bioenergy capacity',
      frFR: 'Capacité bioénergie',
      deDE: 'Bioenergie-Kapazität',
    },
    group: {
      enUS: 'Land and food',
      frFR: 'Terre et alimentation',
      deDE: 'Land und Ernährung',
    },
    headline: {
      enUS: 'Resources and land use',
      frFR: 'Ressources et utilisation des terres',
      deDE: 'Ressourcen und Landnutzung',
    },
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_alt-protein',
    title: {
      enUS: 'Alternative protein source',
      frFR: 'Source protéine alternative',
      deDE: 'Alternative Proteinquellen',
    },
    group: {
      enUS: 'Land and food',
      frFR: 'Terre et alimentation',
      deDE: 'Land und Ernährung',
    },
    headline: {
      enUS: 'Resources and land use',
      frFR: 'Ressources et utilisation des terres',
      deDE: 'Ressourcen und Landnutzung',
    },
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_climate-smart-forestry',
    title: {
      enUS: 'Forestry practices',
      frFR: 'Pratiques forestières',
      deDE: 'Forstwirtschaftliche Praktiken',
    },
    group: {
      enUS: 'Land and food',
      frFR: 'Terre et alimentation',
      deDE: 'Land und Ernährung',
    },
    headline: {
      enUS: 'Resources and land use',
      frFR: 'Ressources et utilisation des terres',
      deDE: 'Ressourcen und Landnutzung',
    },
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_land-man',
    title: {
      enUS: 'Land management',
      frFR: 'Gestion des terres',
      deDE: 'Landmanagement',
    },
    group: {
      enUS: 'Land and food',
      frFR: 'Terre et alimentation',
      deDE: 'Land und Ernährung',
    },
    headline: {
      enUS: 'Resources and land use',
      frFR: 'Ressources et utilisation des terres',
      deDE: 'Ressourcen und Landnutzung',
    },
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_biomass-hierarchy',
    title: {
      enUS: 'Hierarchy for biomass end-uses',
      frFR: 'Hiérarchie biomasse',
      deDE: 'Biomasse-Hierarchie',
    },
    group: {
      enUS: 'Land and food',
      frFR: 'Terre et alimentation',
      deDE: 'Land und Ernährung',
    },
    headline: {
      enUS: 'Resources and land use',
      frFR: 'Ressources et utilisation des terres',
      deDE: 'Ressourcen und Landnutzung',
    },
    range: [1, 2, 3, 4],
    type: 'char',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_biodiversity',
    title: {
      enUS: 'Area set aside for nature...',
      frFR: 'Zones pour la nature...',
      deDE: 'Naturschutzflächen...',
    },
    group: {
      enUS: 'Biodiversity',
      frFR: 'Biodiversité',
      deDE: 'Biodiversität',
    },
    headline: {
      enUS: 'Resources and land use',
      frFR: 'Ressources et utilisation des terres',
      deDE: 'Ressourcen und Landnutzung',
    },
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_land-prioritisation',
    title: {
      enUS: '...from agriculture or forestry',
      frFR: '...agriculture ou foresterie',
      deDE: '...aus Landwirtschaft/Forstwirtschaft',
    },
    group: {
      enUS: 'Biodiversity',
      frFR: 'Biodiversité',
      deDE: 'Biodiversität',
    },
    headline: {
      enUS: 'Resources and land use',
      frFR: 'Ressources et utilisation des terres',
      deDE: 'Ressourcen und Landnutzung',
    },
    range: [],
    type: 'char',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_pop',
    title: {
      enUS: 'Population',
      frFR: 'Population',
      deDE: 'Bevölkerung',
    },
    group: {
      enUS: 'Demographics & long-term',
      frFR: 'Démographie & long terme',
      deDE: 'Demografie & Langfristig',
    },
    headline: {
      enUS: 'Boundary conditions',
      frFR: 'Conditions limites',
      deDE: 'Randbedingungen',
    },
    range: [],
    type: 'char',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_urbpop',
    title: {
      enUS: 'Urban population',
      frFR: 'Population urbaine',
      deDE: 'Stadtbevölkerung',
    },
    group: {
      enUS: 'Demographics & long-term',
      frFR: 'Démographie & long terme',
      deDE: 'Demografie & Langfristig',
    },
    headline: {
      enUS: 'Boundary conditions',
      frFR: 'Conditions limites',
      deDE: 'Randbedingungen',
    },
    range: [],
    type: 'char',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_ems-after-2050',
    title: {
      enUS: 'EU emissions after 2050',
      frFR: 'Émissions UE après 2050',
      deDE: 'EU-Emissionen nach 2050',
    },
    group: {
      enUS: 'Demographics & long-term',
      frFR: 'Démographie & long terme',
      deDE: 'Demografie & Langfristig',
    },
    headline: {
      enUS: 'Boundary conditions',
      frFR: 'Conditions limites',
      deDE: 'Randbedingungen',
    },
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_food-net-import',
    title: {
      enUS: 'Food self-sufficiency',
      frFR: 'Autosuffisance alimentaire',
      deDE: 'Selbstversorgung mit Lebensmitteln',
    },
    group: {
      enUS: 'Domestic supply',
      frFR: 'Approvisionnement interne',
      deDE: 'Inlandsversorgung',
    },
    headline: {
      enUS: 'Boundary conditions',
      frFR: 'Conditions limites',
      deDE: 'Randbedingungen',
    },
    range: [1, 2, 3, 4],
    type: 'char',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_product-net-import',
    title: {
      enUS: 'Product manufacturing',
      frFR: 'Fabrication produits',
      deDE: 'Produktherstellung',
    },
    group: {
      enUS: 'Domestic supply',
      frFR: 'Approvisionnement interne',
      deDE: 'Inlandsversorgung',
    },
    headline: {
      enUS: 'Boundary conditions',
      frFR: 'Conditions limites',
      deDE: 'Randbedingungen',
    },
    range: [],
    type: 'char',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_material-net-import',
    title: {
      enUS: 'Material production',
      frFR: 'Production matériaux',
      deDE: 'Materialproduktion',
    },
    group: {
      enUS: 'Domestic supply',
      frFR: 'Approvisionnement interne',
      deDE: 'Inlandsversorgung',
    },
    headline: {
      enUS: 'Boundary conditions',
      frFR: 'Conditions limites',
      deDE: 'Randbedingungen',
    },
    range: [],
    type: 'char',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_temp',
    title: {
      enUS: 'Global mitigation effort',
      frFR: 'Effort mitigation mondial',
      deDE: 'Globales Mitigationsziel',
    },
    group: {
      enUS: 'Constraints',
      frFR: 'Contraintes',
      deDE: 'Einschränkungen',
    },
    headline: {
      enUS: 'Boundary conditions',
      frFR: 'Conditions limites',
      deDE: 'Randbedingungen',
    },
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_passenger_aviation-pkm',
    title: {
      enUS: 'Aviation travel',
      frFR: 'Distance aérienne',
      deDE: 'Flugdistanz',
    },
    group: {
      enUS: 'Travel',
      frFR: 'Voyages',
      deDE: 'Reisen',
    },
    headline: {
      enUS: 'Key behaviours',
      frFR: 'Comportements clés',
      deDE: 'Schlüsselverhalten',
    },
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_pv-capacity',
    title: {
      enUS: 'Solar',
      frFR: 'Solaire',
      deDE: 'Solar',
    },
    group: {
      enUS: 'Power',
      frFR: 'Production énergie',
      deDE: 'Stromerzeugung',
    },
    headline: {
      enUS: 'Technology and fuels',
      frFR: 'Technologie et combustibles',
      deDE: 'Technik und Brennstoffe',
    },
    popupText: {
      enUS: "This lever sets an upper limit on how much new solar photovoltaic (PV) capacity can be built in Switzerland by 2050, relative to today's installed capacity and the estimated technical potential of suitable roofs and sites. Unlike the nuclear lever, it doesn't force that capacity to be built — the model's cost-optimized power dispatch decides how much of the allowed range is actually used.\n\nLevel 1: No additional solar capacity beyond what is already installed today.\nLevel 2: Moderate expansion allowed, up to roughly a third of the way to full technical potential.\nLevel 3: Substantial expansion allowed, up to roughly two thirds of the way to full technical potential.\nLevel 4: Solar capacity can expand up to its full estimated technical potential (about 47 GW).",
      frFR: "Ce levier fixe une limite supérieure à la quantité de nouvelle capacité solaire photovoltaïque (PV) qui peut être installée en Suisse d'ici 2050, par rapport à la capacité actuelle et au potentiel technique estimé des toits et sites adaptés. Contrairement au levier nucléaire, il n'impose pas la construction de cette capacité — c'est l'optimisation des coûts du dispatching électrique du modèle qui détermine dans quelle mesure cette limite est effectivement utilisée.\n\nNiveau 1 : aucune capacité solaire supplémentaire n'est ajoutée au-delà de ce qui est déjà installé aujourd'hui.\nNiveau 2 : expansion modérée autorisée, jusqu'à environ un tiers du chemin vers le plein potentiel technique.\nNiveau 3 : expansion importante autorisée, jusqu'à environ deux tiers du chemin vers le plein potentiel technique.\nNiveau 4 : la capacité solaire peut être développée jusqu'à son plein potentiel technique estimé (environ 47 GW).",
      deDE: 'Dieser Hebel legt eine Obergrenze für den Zubau neuer Photovoltaik (PV)-Kapazität bis 2050 in der Schweiz fest, ausgehend von der heute installierten Kapazität und dem geschätzten technischen Potenzial geeigneter Dächer und Standorte. Anders als beim Kernkraft-Hebel wird dieser Zubau dadurch nicht erzwungen — die kostenoptimierte Einsatzplanung des Modells entscheidet, in welchem Umfang dieser Spielraum tatsächlich genutzt wird.\n\nStufe 1: Es wird keine zusätzliche Solarkapazität über die heute installierte hinaus zugebaut.\nStufe 2: Moderater Ausbau möglich, bis zu etwa einem Drittel des Wegs zum vollen technischen Potenzial.\nStufe 3: Deutlicher Ausbau möglich, bis zu etwa zwei Dritteln des Wegs zum vollen technischen Potenzial.\nStufe 4: Die Solarkapazität kann bis zum geschätzten vollen technischen Potenzial ausgebaut werden (etwa 47 GW).',
    },
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_onshore-wind-capacity',
    title: {
      enUS: 'Wind',
      frFR: 'Éolien',
      deDE: 'Wind',
    },
    group: {
      enUS: 'Power',
      frFR: 'Production énergie',
      deDE: 'Stromerzeugung',
    },
    headline: {
      enUS: 'Technology and fuels',
      frFR: 'Technologie et combustibles',
      deDE: 'Technik und Brennstoffe',
    },
    popupText: {
      enUS: "This lever sets an upper limit on how much new onshore wind capacity can be built in Switzerland by 2050, relative to today's installed capacity and the estimated technical potential of suitable sites. Unlike the nuclear lever, it doesn't force that capacity to be built — the model's cost-optimized power dispatch decides how much of the allowed range is actually used.\n\nLevel 1: No additional wind capacity beyond what is already installed today.\nLevel 2: Moderate expansion allowed, up to roughly a third of the way to full technical potential.\nLevel 3: Substantial expansion allowed, up to roughly two thirds of the way to full technical potential.\nLevel 4: Wind capacity can expand up to its full estimated technical potential (about 11.9 GW, or roughly 3,950 turbines).",
      frFR: "Ce levier fixe une limite supérieure à la quantité de nouvelle capacité éolienne terrestre qui peut être installée en Suisse d'ici 2050, par rapport à la capacité actuelle et au potentiel technique estimé des sites adaptés. Contrairement au levier nucléaire, il n'impose pas la construction de cette capacité — c'est l'optimisation des coûts du dispatching électrique du modèle qui détermine dans quelle mesure cette limite est effectivement utilisée.\n\nNiveau 1 : aucune capacité éolienne supplémentaire n'est ajoutée au-delà de ce qui est déjà installé aujourd'hui.\nNiveau 2 : expansion modérée autorisée, jusqu'à environ un tiers du chemin vers le plein potentiel technique.\nNiveau 3 : expansion importante autorisée, jusqu'à environ deux tiers du chemin vers le plein potentiel technique.\nNiveau 4 : la capacité éolienne peut être développée jusqu'à son plein potentiel technique estimé (environ 11,9 GW, soit près de 3 950 éoliennes).",
      deDE: "Dieser Hebel legt eine Obergrenze für den Zubau neuer Onshore-Windkapazität bis 2050 in der Schweiz fest, ausgehend von der heute installierten Kapazität und dem geschätzten technischen Potenzial geeigneter Standorte. Anders als beim Kernkraft-Hebel wird dieser Zubau dadurch nicht erzwungen — die kostenoptimierte Einsatzplanung des Modells entscheidet, in welchem Umfang dieser Spielraum tatsächlich genutzt wird.\n\nStufe 1: Es wird keine zusätzliche Windkapazität über die heute installierte hinaus zugebaut.\nStufe 2: Moderater Ausbau möglich, bis zu etwa einem Drittel des Wegs zum vollen technischen Potenzial.\nStufe 3: Deutlicher Ausbau möglich, bis zu etwa zwei Dritteln des Wegs zum vollen technischen Potenzial.\nStufe 4: Die Windkapazität kann bis zum geschätzten vollen technischen Potenzial ausgebaut werden (etwa 11,9 GW, das entspricht rund 3'950 Windturbinen).",
    },
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_nuclear-capacity',
    title: {
      enUS: 'Nuclear',
      frFR: 'Nucléaire',
      deDE: 'Kernkraft',
    },
    group: {
      enUS: 'Power',
      frFR: 'Production énergie',
      deDE: 'Stromerzeugung',
    },
    headline: {
      enUS: 'Technology and fuels',
      frFR: 'Technologie et combustibles',
      deDE: 'Technik und Brennstoffe',
    },
    popupText: {
      enUS: "This lever controls the future of Switzerland's nuclear fleet, based on whether the Gösgen and Leibstadt plants are retired or kept running, and whether new nuclear capacity is built.\n\nLevel 1: Business-as-usual phase-out — all existing reactors retire on their expected end-of-life dates, with nuclear power phased out entirely by around 2045.\nLevel 2: Gösgen also retires as scheduled, but Leibstadt keeps running beyond its currently expected end date.\nLevel 3: Both Gösgen and Leibstadt keep running, with no new nuclear capacity built.\nLevel 4: Same as level 3, plus around 2 GW of new nuclear capacity coming online by 2050.",
      frFR: "Ce levier détermine l'avenir du parc nucléaire suisse, selon que les centrales de Gösgen et Leibstadt soient mises à l'arrêt ou poursuivent leur exploitation, et selon la possibilité de construire de nouvelles capacités nucléaires.\n\nNiveau 1 : sortie du nucléaire au fil de l'eau — tous les réacteurs existants sont mis à l'arrêt à la fin de leur durée de vie prévue, avec une sortie complète du nucléaire vers 2045.\nNiveau 2 : Gösgen est également mise à l'arrêt comme prévu, mais Leibstadt continue de fonctionner au-delà de sa date de fin de vie actuellement prévue.\nNiveau 3 : Gösgen et Leibstadt continuent toutes deux de fonctionner, sans nouvelle capacité nucléaire construite.\nNiveau 4 : comme le niveau 3, avec en plus environ 2 GW de nouvelle capacité nucléaire mise en service d'ici 2050.",
      deDE: 'Dieser Hebel bestimmt die Zukunft der Schweizer Kernkraftflotte – abhängig davon, ob die Kraftwerke Gösgen und Leibstadt stillgelegt werden oder weiterlaufen, sowie von der Möglichkeit, neue Kernkraftkapazitäten zu bauen.\n\nStufe 1: Ausstieg im Business-as-usual-Szenario — alle bestehenden Reaktoren werden am Ende ihrer erwarteten Lebensdauer stillgelegt, vollständiger Kernenergieausstieg bis etwa 2045.\nStufe 2: Auch Gösgen wird wie geplant stillgelegt, Leibstadt läuft jedoch über sein derzeit erwartetes Enddatum hinaus weiter.\nStufe 3: Sowohl Gösgen als auch Leibstadt laufen weiter, es werden keine neuen Kernkraftkapazitäten gebaut.\nStufe 4: Wie Stufe 3, zusätzlich werden bis 2050 rund 2 GW neue Kernkraftkapazität in Betrieb genommen.',
    },
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_eol-waste-management',
    title: {
      enUS: 'Waste management',
      frFR: 'Gestion des déchets',
      deDE: 'Abfallwirtschaft',
    },
    group: {
      enUS: 'Manufacturing',
      frFR: 'Fabrication',
      deDE: 'Fertigung',
    },
    headline: {
      enUS: 'Technology and fuels',
      frFR: 'Technologie et combustibles',
      deDE: 'Technik und Brennstoffe',
    },
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_eol-material-recovery',
    title: {
      enUS: 'Material recovery',
      frFR: 'Récupération matériaux',
      deDE: 'Materialrückgewinnung',
    },
    group: {
      enUS: 'Manufacturing',
      frFR: 'Fabrication',
      deDE: 'Fertigung',
    },
    headline: {
      enUS: 'Technology and fuels',
      frFR: 'Technologie et combustibles',
      deDE: 'Technik und Brennstoffe',
    },
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_harvest-rate',
    title: {
      enUS: 'Harvest rate',
      frFR: 'Taux de récolte',
      deDE: 'Erntequote',
    },
    group: {
      enUS: 'Manufacturing',
      frFR: 'Fabrication',
      deDE: 'Fertigung',
    },
    headline: {
      enUS: 'Technology and fuels',
      frFR: 'Technologie et combustibles',
      deDE: 'Technik und Brennstoffe',
    },
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
  {
    code: 'lever_footprint',
    title: {
      enUS: 'Footprint',
      frFR: 'Empreinte',
      deDE: 'Fußabdruck',
    },
    group: {
      enUS: 'Life Cycle Assessment',
      frFR: 'Analyse du Cycle de Vie',
      deDE: 'Lebenszyklusanalyse',
    },
    headline: {
      enUS: 'Environmental impact',
      frFR: 'Impact environnemental',
      deDE: 'Umweltauswirkungen',
    },
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#CFE3F7', label: 'lever.difficulty.easy' },
      { min: 2, max: 2, color: '#92BFEB', label: 'lever.difficulty.moderate' },
      { min: 3, max: 3, color: '#559ADE', label: 'lever.difficulty.hard' },
      { min: 4, max: 4, color: '#1876D2', label: 'lever.difficulty.ambitious' },
    ],
  },
];
