import { type Sector } from 'src/utils/sectors';
export const sectors: Sector[] = [
  {
    label: {
      enUS: 'Overall',
      frFR: "Vue d'ensemble",
      deDE: 'Gesamt',
    },
    value: 'overall',
    icon: 'dashboard',
    description: {
      enUS: 'View comprehensive overview across all sectors and key metrics',
      frFR: "Vue d'ensemble complète de tous les secteurs et indicateurs clés",
      deDE: 'Umfassende Übersicht über alle Sektoren und wichtige Kennzahlen',
    },
    levers: [],
  },
  {
    label: {
      enUS: 'Buildings',
      frFR: 'Bâtiments',
      deDE: 'Gebäude',
    },
    value: 'buildings',
    icon: 'apartment',
    description: {
      enUS: 'Model heating, cooling, and energy efficiency improvements in residential and commercial buildings',
      frFR: "Modélisez le chauffage, la climatisation et les améliorations de l'efficacité énergétique dans les bâtiments résidentiels et commerciaux",
      deDE: 'Modellieren Sie Heizung, Kühlung und Energieeffizienzverbesserungen in Wohn- und Geschäftsgebäuden',
    },
    levers: [
      'lever_heatcool-behaviour',
      'lever_floor-intensity',
      'lever_building-renovation-rate',
      'lever_heating-technology-fuel',
      'lever_heating-efficiency',
      'lever_appliance-own',
      'lever_appliance-use',
      'lever_appliance-efficiency',
    ],
  },
  {
    label: {
      enUS: 'Transport',
      frFR: 'Transport',
      deDE: 'Transport',
    },
    value: 'transport',
    icon: 'bike_scooter',
    description: {
      enUS: 'Analyze transitions to electric vehicles, public transport, and sustainable mobility',
      frFR: 'Analysez les transitions vers les véhicules électriques, les transports publics et la mobilité durable',
      deDE: 'Analysieren Sie Übergänge zu Elektrofahrzeugen, öffentlichen Verkehrsmitteln und nachhaltiger Mobilität',
    },
    levers: [
      'lever_pkm',
      'lever_passenger_aviation-pkm',
      'lever_passenger_modal-share',
      'lever_passenger_occupancy',
      'lever_passenger_utilization-rate',
      'lever_fuel-mix',
      'lever_passenger_technology-share_new',
      'lever_passenger_veh-efficiency_new',
      'lever_freight_modal-share',
      'lever_freight_technology-share_new',
      'lever_freight_tkm',
      'lever_freight_utilization-rate',
      'lever_freight_vehicle-efficiency_new',
    ],
  },
  {
    label: {
      enUS: 'Energy',
      frFR: 'Énergie',
      deDE: 'Energie',
    },
    value: 'energy',
    icon: 'bolt',
    description: {
      enUS: 'Explore energy production, distribution, and consumption patterns',
      frFR: "Explorez la production, la distribution et les modèles de consommation d'énergie",
      deDE: 'Erkunden Sie Energieproduktion, -verteilung und -verbrauchsmuster',
    },
    levers: [
      'lever_pkm',
      'lever_passenger_technology-share_new',
      'lever_building-renovation-rate',
      'lever_heating-technology-fuel',
    ],
  },
  {
    label: {
      enUS: 'Forestry',
      frFR: 'Foresterie',
      deDE: 'Forstwirtschaft',
    },
    value: 'forestry',
    icon: 'forest',
    description: {
      enUS: 'Understand carbon sequestration potential and sustainable forest management',
      frFR: 'Comprenez le potentiel de séquestration du carbone et la gestion durable des forêts',
      deDE: 'Verstehen Sie das Kohlenstoffbindungspotenzial und nachhaltige Waldwirtschaft',
    },
    levers: ['lever_harvest-rate'],
  },
  {
    label: {
      enUS: 'Agriculture',
      frFR: 'Agriculture',
      deDE: 'Landwirtschaft',
    },
    value: 'agriculture',
    icon: 'agriculture',
    description: {
      enUS: 'Explore sustainable farming practices and emission reduction strategies',
      frFR: 'Explorez les pratiques agricoles durables et les stratégies de réduction des émissions',
      deDE: 'Erkunden Sie nachhaltige landwirtschaftliche Praktiken und Strategien zur Emissionsreduzierung',
    },
    disabled: true,
    levers: [
      'lever_kcal-req',
      'lever_diet',
      'lever_fwaste',
      'lever_climate-smart-crop',
      'lever_climate-smart-livestock',
      'lever_bioenergy-capacity',
      'lever_alt-protein',
      'lever_biomass-hierarchy',
    ],
  },
];
