import { type Sector } from 'src/utils/sectors';
export const sectors: Sector[] = [
  {
    label: {
      enUS: 'Overall',
      frFR: "Vue d'ensemble",
      deDE: 'Gesamt',
    },
    value: 'overall',
    icon: 'dashboard',
    description: {
      enUS: 'View comprehensive overview across all sectors and key metrics',
      frFR: "Vue d'ensemble complète de tous les secteurs et indicateurs clés",
      deDE: 'Umfassende Übersicht über alle Sektoren und wichtige Kennzahlen',
    },
    levers: [],
  },
  {
    label: {
      enUS: 'Buildings',
      frFR: 'Bâtiments',
      deDE: 'Gebäude',
    },
    value: 'buildings',
    icon: 'apartment',
    description: {
      enUS: 'Model heating, cooling, and energy efficiency improvements in residential and commercial buildings',
      frFR: "Modélisez le chauffage, la climatisation et les améliorations de l'efficacité énergétique dans les bâtiments résidentiels et commerciaux",
      deDE: 'Modellieren Sie Heizung, Kühlung und Energieeffizienzverbesserungen in Wohn- und Geschäftsgebäuden',
    },
    levers: [
      'lever_heatcool-behaviour',
      'lever_floor-intensity',
      'lever_building-renovation-rate',
      'lever_heating-technology-fuel',
      'lever_heating-efficiency',
      'lever_appliance-own',
      'lever_appliance-use',
      'lever_appliance-efficiency',
    ],
  },
  {
    label: {
      enUS: 'Transport',
      frFR: 'Transport',
      deDE: 'Transport',
    },
    value: 'transport',
    icon: 'bike_scooter',
    description: {
      enUS: 'Analyze transitions to electric vehicles, public transport, and sustainable mobility',
      frFR: 'Analysez les transitions vers les véhicules électriques, les transports publics et la mobilité durable',
      deDE: 'Analysieren Sie Übergänge zu Elektrofahrzeugen, öffentlichen Verkehrsmitteln und nachhaltiger Mobilität',
    },
    levers: [
      'lever_pkm',
      'lever_passenger_aviation-pkm',
      'lever_passenger_modal-share',
      'lever_passenger_occupancy',
      'lever_passenger_utilization-rate',
      'lever_fuel-mix',
      'lever_passenger_technology-share_new',
      'lever_passenger_veh-efficiency_new',
      'lever_freight_modal-share',
      'lever_freight_technology-share_new',
      'lever_freight_tkm',
      'lever_freight_utilization-rate',
      'lever_freight_vehicle-efficiency_new',
    ],
  },
  {
    label: {
      enUS: 'Energy',
      frFR: 'Énergie',
      deDE: 'Energie',
    },
    value: 'energy',
    icon: 'bolt',
    description: {
      enUS: 'Explore energy production, distribution, and consumption patterns',
      frFR: "Explorez la production, la distribution et les modèles de consommation d'énergie",
      deDE: 'Erkunden Sie Energieproduktion, -verteilung und -verbrauchsmuster',
    },
    levers: [
      'lever_pkm',
      'lever_passenger_technology-share_new',
      'lever_building-renovation-rate',
      'lever_heating-technology-fuel',
    ],
  },
  {
    label: {
      enUS: 'Forestry',
      frFR: 'Foresterie',
      deDE: 'Forstwirtschaft',
    },
    value: 'forestry',
    icon: 'forest',
    description: {
      enUS: 'Understand carbon sequestration potential and sustainable forest management',
      frFR: 'Comprenez le potentiel de séquestration du carbone et la gestion durable des forêts',
      deDE: 'Verstehen Sie das Kohlenstoffbindungspotenzial und nachhaltige Waldwirtschaft',
    },
    levers: ['lever_harvest-rate'],
  },
  {
    label: {
      enUS: 'Agriculture',
      frFR: 'Agriculture',
      deDE: 'Landwirtschaft',
    },
    value: 'agriculture',
    icon: 'agriculture',
    description: {
      enUS: 'Explore sustainable farming practices and emission reduction strategies',
      frFR: 'Explorez les pratiques agricoles durables et les stratégies de réduction des émissions',
      deDE: 'Erkunden Sie nachhaltige landwirtschaftliche Praktiken und Strategien zur Emissionsreduzierung',
    },
    disabled: true,
    levers: [
      'lever_kcal-req',
      'lever_diet',
      'lever_fwaste',
      'lever_climate-smart-crop',
      'lever_climate-smart-livestock',
      'lever_bioenergy-capacity',
      'lever_alt-protein',
      'lever_biomass-hierarchy',
    ],
  },
  {
    label: {
      enUS: 'Dietary habits',
      frFR: 'Habitudes alimentaires',
      deDE: 'Ernährungsgewohnheiten',
    },
    value: 'dietary-habits',
    icon: 'restaurant',
    description: {
      enUS: 'Diet, food demand and the true cost of what we eat',
      frFR: 'Régime alimentaire, demande et coût réel de ce que nous mangeons',
      deDE: 'Ernährung, Nachfrage und die realen Kosten unserer Lebensmittel',
    },
    levers: [
      'lever_diet-adherence',
      'lever_ssr-bev',
      'lever_diet-split-share',
      'lever_diet-split-kcal_crop-cereal',
      'lever_diet-split-kcal_crop-rice',
      'lever_diet-split-kcal_crop-fruit',
      'lever_diet-split-kcal_crop-oilcrop',
      'lever_diet-split-kcal_crop-pulse',
      'lever_diet-split-kcal_crop-starch',
      'lever_diet-split-kcal_crop-veg',
      'lever_diet-split-kcal_pro-bev-beer',
      'lever_diet-split-kcal_pro-bev-bev-alc',
      'lever_diet-split-kcal_pro-bev-bev-fer',
      'lever_diet-split-kcal_pro-bev-wine',
      'lever_diet-split-kcal_pro-crop-processed-sugar',
      'lever_diet-split-kcal_pro-crop-processed-sweet',
      'lever_diet-split-kcal_pro-crop-processed-voil',
      'lever_diet-split-kcal_pro-liv-abp-dairy-milk',
      'lever_diet-split-kcal_pro-liv-abp-hens-egg',
      'lever_diet-split-kcal_pro-liv-abp-processed-afat',
      'lever_diet-split-kcal_pro-liv-abp-processed-offal',
      'lever_diet-split-kcal_pro-liv-meat-bovine',
      'lever_diet-split-kcal_pro-liv-meat-oth-animal',
      'lever_diet-split-kcal_pro-liv-meat-pig',
      'lever_diet-split-kcal_pro-liv-meat-poultry',
      'lever_diet-split-kcal_pro-liv-meat-sheep',
      'lever_diet-split-kcal_seafood-dfish',
      'lever_diet-split-kcal_seafood-ffish',
      'lever_diet-split-kcal_seafood-oth-aq-animal',
      'lever_diet-split-kcal_seafood-pfish',
      'lever_diet-split-kcal_seafood-seafood',
      'lever_diet-split-kcal_stm-cocoa',
      'lever_diet-split-kcal_stm-coffee',
      'lever_diet-split-kcal_stm-tea',
      'lever_share-processed-food_crop-cereal-whole',
      'lever_share-processed-food_unprocessed-meat',
      'lever_share-kcal-processed-food_crop-cereal-whole',
      'lever_share-kcal-processed-food_unprocessed-meat',
      'lever_share-organic',
      'lever_pop',
      'lever_ruminant-feed',
      'lever_food-net-import',
      'lever_ssr-liv',
      'lever_ssr-liv-abp-dairy-milk',
      'lever_ssr-liv-abp-hens-egg',
      'lever_ssr-liv-meat-poultry',
      'lever_ssr-liv-meat-pig',
      'lever_ssr-liv-meat-bovine',
      'lever_ssr-liv-meat-sheep',
      'lever_ssr-liv-meat-oth-animal',
      'lever_ssr-feed-pro',
      'lever_crop-losses',
      'lever_ssr-crop-cereal',
      'lever_ssr-crop-fruit',
      'lever_ssr-crop-veg',
      'lever_ssr-crop-pulse',
      'lever_ssr-crop-rice',
      'lever_ssr-crop-oilcrop',
      'lever_ssr-crop-sugarcrop',
      'lever_ssr-crop-starch',
      'lever_ssr-bev-beer',
      'lever_ssr-bev-wine',
      'lever_ssr-bev-bev-alc',
      'lever_ssr-bev-bev-fer',
      'lever_ssr-pro-sugar',
      'lever_ssr-pro-sweet',
      'lever_ssr-pro-voil',
      'lever_crop-share-organic',
      'lever_crop-share-extensive',
      'lever_crop-share-intensive',
      'lever_livestock-losses',
      'lever_livestock-yield',
      'lever_slaughter-rates',
      'lever_livestock-density',
      'lever_livestock-enteric',
      'lever_livestock-manure',
      'lever_feed-ration',
    ],
  },
];
