# Multi-stage
# 1) Node image for building frontend assets
# 2) nginx stage to serve frontend assets

# 1) Build of frontend assets
# Node stage
FROM node:14 AS webtool_builder

# Get build argument and set environment variable
ARG APP_ENV=prod
ENV REACT_APP_ENV=$APP_ENV
ARG APP_PROJECT=patex
ENV REACT_APP_PROJECT=$APP_PROJECT

# Root directory in the container
WORKDIR /webtool

# Add `/app/node_modules/.bin` to $PATH
ENV PATH /webtool/node_modules/.bin:$PATH

# Copy all source files for production
COPY ./src .
COPY ./public .
# Install node dependencies
RUN yarn install --production

# Build the app
RUN yarn build


# 2) Serve frontend assets
# Bundle static assets with nginx
FROM nginx:1.21.0-alpine AS webtool_production

# Set working directory to nginx asset directory
WORKDIR /usr/share/nginx/html

# Remove default nginx static assets
RUN rm -rf *

# Copy built assets from builder
COPY --from=webtool_builder /webtool/build /usr/share/nginx/html

# Add your nginx configuration files
COPY ./webtool/nginx/default.conf.template /etc/nginx/conf.d/default.conf
COPY ./webtool/nginx/* /etc/nginx/templates/

# Copy entrypoint script (dynamic env variables)
COPY ./webtool/public/entrypoint.sh entrypoint.sh
ENTRYPOINT ["./entrypoint.sh"]

# Expose port
EXPOSE 3000

# Start nginx
CMD ["nginx", "-g", "daemon off;"]