name: Quality Checks

on:
  pull_request:
    branches: [main, dev]
  push:
    branches:
      [
        main,
        dev,
        feat/*,
        fix/*,
        hotfix/*,
        feature/*,
        bugfix/*,
        new-app-pierre-guilbert,
      ]

jobs:
  quality:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Lint with Flake8
        run: |
          flake8 backend/src --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 backend/src --count --exit-zero --max-complexity=15 --max-line-length=127 --statistics

      - name: Format with Black
        run: black backend/src --check
