export const PLOT_LABELS: Record<string, string> = {
  'agr_bioenergy-capacity_bgs-tec_digestor[TWh]': 'Biogas, digestor',
  'agr_bioenergy-capacity_bgs-tec_landfill[TWh]': 'Biogas, landfill',
  'agr_bioenergy-capacity_bgs-tec_other-biogases[TWh]': 'Biogas, other',
  'agr_bioenergy-capacity_bgs-tec_ren-mun-wastes[TWh]': 'Biogas, ren-mun-wastes',
  'agr_bioenergy-capacity_bgs-tec_sewage[TWh]': 'Biogas, sewage',
  'agr_bioenergy-capacity_bgs-tec_thermal-biogases[TWh]': 'Biogas, thermal-biogases',
  'agr_bioenergy-capacity_liq-bio-prod_biodiesel_btl[TWh]': 'Biodiesel, Biomass-To-Liquid',
  'agr_bioenergy-capacity_liq-bio-prod_biodiesel_est[TWh]': 'Biodiesel, FAME',
  'agr_bioenergy-capacity_liq-bio-prod_biodiesel_hvo[TWh]': 'Biodiesel, HVO',
  'agr_bioenergy-capacity_liq-bio-prod_biogasoline_ezm[TWh]': 'Biogasoline, cellulosic',
  'agr_bioenergy-capacity_liq-bio-prod_biogasoline_fer[TWh]': 'Biogasoline, ethanol',
  'agr_bioenergy-capacity_liq-bio-prod_biojetkerosene_btl[TWh]':
    'Biojetkerosene, Biomass-To-Liquid',
  'agr_bioenergy-capacity_liq-bio-prod_biojetkerosene_hvo[TWh]': 'Biojetkerosene, HVO',
  'agr_bioenergy_biomass-demand_biogas_bio-waste[TWh]': 'Biogas, bio-wastes',
  'agr_bioenergy_biomass-demand_biogas_energycrop[TWh]': 'Biogas, energy crops',
  'agr_bioenergy_biomass-demand_biogas_manure[TWh]': 'Biogas, manure',
  'agr_bioenergy_biomass-demand_liquid_eth_cereal[TWh]': 'Ethanol, Cereals',
  'agr_bioenergy_biomass-demand_liquid_eth_ind-byproduct[TWh]': 'Ethanol, Industrial-byproducts',
  'agr_bioenergy_biomass-demand_liquid_eth_sugarcrop[TWh]': 'Ethanol, Sugar crops',
  'agr_bioenergy_biomass-demand_liquid_lgn-btl-energycrop[TWh]': 'Biodiesel, Energy-crops',
  'agr_bioenergy_biomass-demand_liquid_lgn-btl-fuelwood-and-res[TWh]': 'Biodiesel, Woody-biomass',
  'agr_bioenergy_biomass-demand_liquid_lgn-ezm-agr-residues[TWh]': 'Ethanol, Agricultural residues',
  'agr_bioenergy_biomass-demand_liquid_lgn-ezm-energycrop[TWh]': 'Ethanol, Energy-crops',
  'agr_bioenergy_biomass-demand_liquid_lgn[TWh]': 'NaN',
  'agr_bioenergy_biomass-demand_liquid_oil_afats[TWh]': 'Biodiesel, Animal fats',
  'agr_bioenergy_biomass-demand_liquid_oil_algae[TWh]': 'Biodiesel, Algae',
  'agr_bioenergy_biomass-demand_liquid_oil_ind-byproduct[TWh]': 'Biodiesel, Industrial-byproducts',
  'agr_bioenergy_biomass-demand_liquid_oil_insect[TWh]': 'Biodiesel, Insect',
  'agr_bioenergy_biomass-demand_liquid_oil_oilcrop[TWh]': 'Biodiesel, Oil crops',
  'agr_bioenergy_biomass-demand_liquid_oil_uco[TWh]': 'Biodiesel, Used Cooking Oil',
  'agr_bioenergy_biomass-demand_solid_animal-waste[TWh]': 'Solid-biomass, animal-wastes',
  'agr_bioenergy_biomass-demand_solid_bagasse[TWh]': 'Solid-biomass, bagasse',
  'agr_bioenergy_biomass-demand_solid_black-liquor[TWh]': 'Solid-biomass, black-liquor',
  'agr_bioenergy_biomass-demand_solid_fuelwood-and-res[TWh]': 'Solid-biomass, woody-biomass',
  'agr_bioenergy_biomass-demand_solid_ren-ind-waste[TWh]':
    'Solid-biomass, municipal renewable wastes',
  'agr_bioenergy_biomass-demand_solid_veg-residues[TWh]': 'Solid-biomass, vegetal-residues',
  'agr_crop-cons_bioenergy[kcal]': 'Bioenergy',
  'agr_crop-cons_feed[kcal]': 'Feedstuffs',
  'agr_crop-cons_food[kcal]': 'Food',
  'agr_crop-cons_non-food[kcal]': 'Non-food',
  'agr_demand_feed_aps_algae[kcal]': 'Algae meals',
  'agr_demand_feed_aps_insect[kcal]': 'Insect meals',
  'agr_demand_feed_crop-cereal[kcal]': 'Cereals',
  'agr_demand_feed_crop-fruit[kcal]': 'Fruits',
  'agr_demand_feed_crop-oilcrop[kcal]': 'Oil crops',
  'agr_demand_feed_crop-pulse[kcal]': 'Pulses',
  'agr_demand_feed_crop-rice[kcal]': 'Rice',
  'agr_demand_feed_crop-starch[kcal]': 'Starchy roots',
  'agr_demand_feed_crop-sugarcrop[kcal]': 'Sugar crops',
  'agr_demand_feed_crop-veg[kcal]': 'Vegetables',
  'agr_demand_feed_fish-fish-meal[kcal]': 'Fish meals',
  'agr_demand_feed_liv-meat-meal[kcal]': 'Meat meal',
  'agr_demand_feed_processed-cake-oilcrop[kcal]': 'Oil crop cakes',
  'agr_demand_feed_processed-molasse-sugarcrop[kcal]': 'Molasse',
  'agr_demand_feed_processed-sugar-sugarcrop[kcal]': 'Sugar',
  'agr_demand_feed_processed-voil-oilcrop[kcal]': 'Oil',
  'agr_domestic-production_afw_algae[kcal]': 'Algae',
  'agr_domestic-production_afw_cereal[kcal]': 'Cereals',
  'agr_domestic-production_afw_fibres-plant-eq[kcal]': 'NaN',
  'agr_domestic-production_afw_fruit[kcal]': 'Fruits',
  'agr_domestic-production_afw_lgn-energycrop[kcal]': 'Energy crops',
  'agr_domestic-production_afw_oilcrop[kcal]': 'Oil crops',
  'agr_domestic-production_afw_pulse[kcal]': 'Pulses',
  'agr_domestic-production_afw_rice[kcal]': 'Rice',
  'agr_domestic-production_afw_starch[kcal]': 'Starchy roots',
  'agr_domestic-production_afw_sugarcrop[kcal]': 'Sugar crops',
  'agr_domestic-production_afw_veg[kcal]': 'Vegetables',
  'agr_domestic-production_liv_insect[kcal]': 'Insects',
  'agr_domestic_production_abp-dairy-milk[kcal]': 'Milk products',
  'agr_domestic_production_abp-hens-egg[kcal]': 'Eggs',
  'agr_domestic_production_abp-processed-afat[kcal]': 'Animal fats',
  'agr_domestic_production_abp-processed-offal[kcal]': 'Animal offals',
  'agr_domestic_production_meat-bovine[kcal]': 'Beef',
  'agr_domestic_production_meat-oth-animals[kcal]': 'Other animals',
  'agr_domestic_production_meat-pig[kcal]': 'Pork',
  'agr_domestic_production_meat-poultry[kcal]': 'Poultry',
  'agr_domestic_production_meat-sheep[kcal]': 'Sheep',
  'agr_elc_energy-demand_total[TWh]': 'NaN',
  'agr_elc_energy-demand_total_cost[MEUR]': 'Electricity cost (AFOLU)',
  'agr_emissions-CH4_crop_burnt-residues[Mt]': 'Burnt residues',
  'agr_emissions-CH4_crop_rice[Mt]': 'Rice',
  'agr_emissions-CH4_liv_enteric_abp-dairy-milk[Mt]': 'Enrteric dairy-animals',
  'agr_emissions-CH4_liv_enteric_abp-hens-egg[Mt]': 'Enteric, laying-poultry',
  'agr_emissions-CH4_liv_enteric_meat-bovine[Mt]': 'Enrteric bovines',
  'agr_emissions-CH4_liv_enteric_meat-oth-animals[Mt]': 'Enteric, other-animals',
  'agr_emissions-CH4_liv_enteric_meat-pig[Mt]': 'Enteric, pigs',
  'agr_emissions-CH4_liv_enteric_meat-poultry[Mt]': 'Enteric, broiler poultry',
  'agr_emissions-CH4_liv_enteric_meat-sheep[Mt]': 'Enteric, sheeps',
  'agr_emissions-CH4_liv_treated_abp-dairy-milk[Mt]': 'Treated manure, dairy-animals',
  'agr_emissions-CH4_liv_treated_abp-hens-egg[Mt]': 'Treated manure, laying-poultry',
  'agr_emissions-CH4_liv_treated_meat-bovine[Mt]': 'Treated manure, bovines',
  'agr_emissions-CH4_liv_treated_meat-oth-animals[Mt]': 'Treated manure, other-animals',
  'agr_emissions-CH4_liv_treated_meat-pig[Mt]': 'Treated manure, pigs',
  'agr_emissions-CH4_liv_treated_meat-poultry[Mt]': 'Treated manure, broiler-poultry',
  'agr_emissions-CH4_liv_treated_meat-sheep[Mt]': 'Treated manure, sheep',
  'agr_emissions-CO2e[Mt]': 'Agriculture',
  'agr_emissions-CO2e_crop-burnt-residues[Mt]': 'Burnt residues',
  'agr_emissions-CO2e_crop-fertilizer[Mt]': 'Fertilizer',
  'agr_emissions-CO2e_crop-rice[Mt]': 'Rice cultivation',
  'agr_emissions-CO2e_crop-soil-residues[Mt]': 'Soil residues',
  'agr_emissions-CO2e_liv-applied-abp-dairy-milk[Mt]': 'Dairy cattle, applied manure',
  'agr_emissions-CO2e_liv-applied-abp-hens-egg[Mt]': 'Laying hens applied manure',
  'agr_emissions-CO2e_liv-applied-meat-bovine[Mt]': 'Cattle, applied manure',
  'agr_emissions-CO2e_liv-applied-meat-oth-animals[Mt]': 'Other-animals, applied manure',
  'agr_emissions-CO2e_liv-applied-meat-pig[Mt]': 'Pigs, applied manure',
  'agr_emissions-CO2e_liv-applied-meat-poultry[Mt]': 'Poultry, applied manure',
  'agr_emissions-CO2e_liv-applied-meat-sheep[Mt]': 'Sheep, applied manure',
  'agr_emissions-CO2e_liv-enteric-abp-dairy-milk[Mt]': 'Dairy cattle, enteric',
  'agr_emissions-CO2e_liv-enteric-abp-hens-egg[Mt]': 'Laying hens, enteric',
  'agr_emissions-CO2e_liv-enteric-meat-bovine[Mt]': 'Cattle, enteric',
  'agr_emissions-CO2e_liv-enteric-meat-oth-animals[Mt]': 'Other-animals, enteric',
  'agr_emissions-CO2e_liv-enteric-meat-pig[Mt]': 'Pigs, enteric',
  'agr_emissions-CO2e_liv-enteric-meat-poultry[Mt]': 'Poultry, enteric',
  'agr_emissions-CO2e_liv-enteric-meat-sheep[Mt]': 'Sheep, enteric',
  'agr_emissions-CO2e_liv-pasture-abp-dairy-milk[Mt]': 'Dairy cattle, pasture',
  'agr_emissions-CO2e_liv-pasture-abp-hens-egg[Mt]': 'Laying hens, pasture',
  'agr_emissions-CO2e_liv-pasture-meat-bovine[Mt]': 'Cattle, pasture',
  'agr_emissions-CO2e_liv-pasture-meat-oth-animals[Mt]': 'Other-animals, pasture',
  'agr_emissions-CO2e_liv-pasture-meat-pig[Mt]': 'Pigs, pasture',
  'agr_emissions-CO2e_liv-pasture-meat-poultry[Mt]': 'Poultry, pasture',
  'agr_emissions-CO2e_liv-pasture-meat-sheep[Mt]': 'Sheep, pasture',
  'agr_emissions-CO2e_liv-treated-abp-dairy-milk[Mt]': 'Dairy cattle, treated',
  'agr_emissions-CO2e_liv-treated-abp-hens-egg[Mt]': 'Laying hens, treated',
  'agr_emissions-CO2e_liv-treated-meat-bovine[Mt]': 'Cattle, treated',
  'agr_emissions-CO2e_liv-treated-meat-oth-animals[Mt]': 'Other-animals, treated',
  'agr_emissions-CO2e_liv-treated-meat-pig[Mt]': 'Pigs, treated',
  'agr_emissions-CO2e_liv-treated-meat-poultry[Mt]': 'Poultry, treated',
  'agr_emissions-CO2e_liv-treated-meat-sheep[Mt]': 'Sheep, treated',
  'agr_emissions-N2O_crop_burnt-residues[Mt]': 'Burnt residues',
  'agr_emissions-N2O_crop_fertilizer[Mt]': 'Fertilizers',
  'agr_emissions-N2O_crop_soil-residues[Mt]': 'Soil residues',
  'agr_emissions-N2O_liv_applied_abp-dairy-milk[Mt]': 'Applied manure, dairy-animals',
  'agr_emissions-N2O_liv_applied_abp-hens-egg[Mt]': 'Applied manure, laying-poultry',
  'agr_emissions-N2O_liv_applied_meat-bovine[Mt]': 'Applied manure, bovines',
  'agr_emissions-N2O_liv_applied_meat-oth-animals[Mt]': 'Applied manure, other-animals',
  'agr_emissions-N2O_liv_applied_meat-pig[Mt]': 'Applied manure, pigs',
  'agr_emissions-N2O_liv_applied_meat-poultry[Mt]': 'Applied manure, broiler-poultry',
  'agr_emissions-N2O_liv_applied_meat-sheep[Mt]': 'Applied manure, sheep',
  'agr_emissions-N2O_liv_pasture_abp-dairy-milk[Mt]': 'manure left on pasture, dairy-animals',
  'agr_emissions-N2O_liv_pasture_abp-hens-egg[Mt]': 'manure left on pasture, laying-poultry',
  'agr_emissions-N2O_liv_pasture_meat-bovine[Mt]': 'manure left on pasture, bovines',
  'agr_emissions-N2O_liv_pasture_meat-oth-animals[Mt]': 'manure left on pasture, other-animals',
  'agr_emissions-N2O_liv_pasture_meat-pig[Mt]': 'manure left on pasture, pigs',
  'agr_emissions-N2O_liv_pasture_meat-poultry[Mt]': 'manure left on pasture, broiler-poultry',
  'agr_emissions-N2O_liv_pasture_meat-sheep[Mt]': 'manure left on pasture, sheep',
  'agr_emissions-N2O_liv_treated_abp-dairy-milk[Mt]': 'Treated manure, dairy-animals',
  'agr_emissions-N2O_liv_treated_abp-hens-egg[Mt]': 'Treated manure, laying-poultry',
  'agr_emissions-N2O_liv_treated_meat-bovine[Mt]': 'Treated manure, bovines',
  'agr_emissions-N2O_liv_treated_meat-oth-animals[Mt]': 'Treated manure, other-animals',
  'agr_emissions-N2O_liv_treated_meat-pig[Mt]': 'Treated manure, pigs',
  'agr_emissions-N2O_liv_treated_meat-poultry[Mt]': 'Treated manure, broiler-poultry',
  'agr_emissions-N2O_liv_treated_meat-sheep[Mt]': 'Treated manure, sheep',
  'agr_energy-cost[MEUR]': 'Fossil fuel cost (Agriculture)',
  'agr_energy-demand[TWh]': 'Agriculture',
  'agr_energy-demand_electricity[TWh]': 'Electricity',
  'agr_energy-demand_gas-ff-natural[TWh]': 'Natural gas',
  'agr_energy-demand_heat[TWh]': 'Heat',
  'agr_energy-demand_liquid-ff-diesel[TWh]': 'Diesel',
  'agr_energy-demand_liquid-ff-fuel-oil[TWh]': 'Fuel-Oil',
  'agr_energy-demand_liquid-ff-gasoline[TWh]': 'Gasoline',
  'agr_energy-demand_liquid-ff-lpg[TWh]': 'LPG',
  'agr_energy-demand_oth[TWh]': 'Other',
  'agr_energy-demand_solid-ff-coal[TWh]': 'Coal',
  'agr_energy-demand_total[TWh]': 'Agriculture',
  'agr_fuel-cost_gas-ff-natural[MEUR]': 'Cost of natural gas for agr',
  'agr_fuel-cost_liquid-ff-oil[MEUR]': 'Cost of crude oil for agr',
  'agr_fuel-cost_solid-ff-coal[MEUR]': 'Cost of coal for agr',
  'agr_input-use_app_liming[t]': 'NaN',
  'agr_input-use_app_urea[t]': 'NaN',
  'agr_input-use_emissions-CO2_fuel[Mt]': 'Fuel',
  'agr_input-use_emissions-CO2_liming[Mt]': 'Liming',
  'agr_input-use_emissions-CO2_urea[Mt]': 'Urea',
  'agr_input-use_nitrogen[t]': 'NaN',
  'agr_input-use_pesticide[t]': 'NaN',
  'agr_input-use_phosphate[t]': 'NaN',
  'agr_input-use_potash[t]': 'NaN',
  'agr_liv_population_abp-dairy-milk[lsu]': 'Dairy cattle',
  'agr_liv_population_abp-hens-egg[lsu]': 'Laying hens',
  'agr_liv_population_meat-bovine[lsu]': 'Bovine',
  'agr_liv_population_meat-oth-animals[lsu]': 'Other animals',
  'agr_liv_population_meat-pig[lsu]': 'Pigs',
  'agr_liv_population_meat-poultry[lsu]': 'Poultry',
  'agr_liv_population_meat-sheep[lsu]': 'Sheep',
  'agr_total-bioenergy-demand_agr_gas_biogas[TWh]': 'Biogas',
  'agr_total-bioenergy-demand_agr_liquid_biodiesels[TWh]': 'Biodiesel',
  'agr_total-bioenergy-demand_agr_liquid_ethanol[TWh]': 'Ethanol',
  'agr_total-bioenergy-demand_agr_liquid_oth[TWh]': 'Other-liquid biofuels',
  'agr_total-bioenergy-demand_agr_solid-wood[TWh]': 'Wood',
  'agr_total-bioenergy-demand_bld_gas[TWh]': 'NaN',
  'agr_total-bioenergy-demand_bld_liquid_biodiesel[TWh]': 'NaN',
  'agr_total-bioenergy-demand_bld_liquid_biogasoline[TWh]': 'NaN',
  'agr_total-bioenergy-demand_bld_solid_pellets[TWh]': 'NaN',
  'agr_total-bioenergy-demand_bld_solid_woodlogs[TWh]': 'NaN',
  'agr_total-bioenergy-demand_elc_biogases[TWh]': 'NaN',
  'agr_total-bioenergy-demand_elc_solid-biofuel[TWh]': 'NaN',
  'agr_total-bioenergy-demand_gas[TWh]': 'Bioenergy gaseous',
  'agr_total-bioenergy-demand_ind_gas-bio[TWh]': 'Gaseous',
  'agr_total-bioenergy-demand_ind_liquid-bio[TWh]': 'NaN',
  'agr_total-bioenergy-demand_ind_solid-bio[TWh]': 'Liquid',
  'agr_total-bioenergy-demand_tra_gas[TWh]': 'NaN',
  'agr_total-bioenergy-demand_tra_liquid_biodiesel[TWh]': 'NaN',
  'agr_total-bioenergy-demand_tra_liquid_ethanol[TWh]': 'NaN',
  'agr_total-bioenergy-demand_tra_liquid_jetfuel[TWh]': 'NaN',
  'air_exposure[ug/m3]': 'NaN',
  'air_mortality-cost[MEUR]': 'NaN',
  'air_mortality[deaths]': 'NaN',
  'air_mortality_baseline[deaths]': 'NaN',
  'amm_CO2-emissions-CC_ammonia_amm-tech[Mt]': 'Ammonia',
  'amm_elc_energy-demand_total[TWh]': 'NaN',
  'amm_elc_energy-demand_total_cost[MEUR]': 'Electricity cost (ammonia)',
  'amm_emissions-CH4[Mt]': 'CH4',
  'amm_emissions-CO2[Mt]': 'CO2',
  'amm_emissions-CO2e[Mt]': 'Industry (Ammonia)',
  'amm_emissions-N2O[Mt]': 'N2O',
  'amm_energy-demand_ammonia[TWh]': 'Ammonia',
  'amm_energy-demand_electricity[TWh]': 'Electricity',
  'amm_energy-demand_gas-bio[TWh]': 'Gaseous Biomass',
  'amm_energy-demand_gas-ff-natural[TWh]': 'Natural Gas',
  'amm_energy-demand_hydrogen[TWh]': 'Hydrogen',
  'amm_energy-demand_liquid-bio[TWh]': 'Liquid Biomass',
  'amm_energy-demand_liquid-ff-diesel[TWh]': 'NaN',
  'amm_energy-demand_liquid-ff-fuel-oil[TWh]': 'NaN',
  'amm_energy-demand_liquid-ff-oil[TWh]': 'Oil',
  'amm_energy-demand_solid-bio[TWh]': 'Solid Biomass',
  'amm_energy-demand_solid-ff-coal[TWh]': 'Coal',
  'amm_energy-demand_solid-waste[TWh]': 'Waste',
  'amm_energy-demand_total[TWh]': 'Ammonia',
  'amm_material-production_ammonia[Mt]': 'Ammonia',
  'bdy_emissions-CH4[Mt]': 'CH4',
  'bdy_emissions-CO2[Mt]': 'CO2',
  'bdy_emissions-CO2e[Mt]': 'Biodiversity',
  'bdy_emissions-N2O[Mt]': 'N2O',
  'bld_CO2-emissions_heating_B[Mt]': 'A, B',
  'bld_CO2-emissions_heating_C[Mt]': 'C',
  'bld_CO2-emissions_heating_D[Mt]': 'D',
  'bld_CO2-emissions_heating_E[Mt]': 'E',
  'bld_CO2-emissions_heating_F[Mt]': 'F, G',
  'bld_CO2-emissions_heating_coal[Mt]': 'Coal',
  'bld_CO2-emissions_heating_district-heating[Mt]': 'District-heating',
  'bld_CO2-emissions_heating_electricity[Mt]': 'Electricity',
  'bld_CO2-emissions_heating_gas[Mt]': 'Gas',
  'bld_CO2-emissions_heating_heat-pump[Mt]': 'Heat-pump',
  'bld_CO2-emissions_heating_heating-oil[Mt]': 'Heating-oil',
  'bld_CO2-emissions_heating_other[Mt]': 'Other',
  'bld_CO2-emissions_heating_solar[Mt]': 'Solar-heat',
  'bld_CO2-emissions_heating_wood[Mt]': 'Wood',
  'bld_appliances_costs_comp[MEUR]': 'Computer',
  'bld_appliances_costs_dishwasher[MEUR]': 'Dishwasher',
  'bld_appliances_costs_dryer[MEUR]': 'Dryer',
  'bld_appliances_costs_freezer[MEUR]': 'Freezer',
  'bld_appliances_costs_fridge[MEUR]': 'Fridge',
  'bld_appliances_costs_phone[MEUR]': '(Smart)Phones',
  'bld_appliances_costs_tv[MEUR]': 'TV',
  'bld_appliances_costs_wmachine[MEUR]': 'Washine machine',
  'bld_capex_comp[billion_EUR]': 'Computer',
  'bld_capex_dishwasher[billion_EUR]': 'Dishwasher',
  'bld_capex_dryer[billion_EUR]': 'Dryer',
  'bld_capex_freezer[billion_EUR]': 'Freezer',
  'bld_capex_fridge[billion_EUR]': 'Fridge',
  'bld_capex_phone[billion_EUR]': 'Phone',
  'bld_capex_reno-dep-mfh[billion_EUR]': 'Multi-family homes, deep',
  'bld_capex_reno-dep-off_education[billion_EUR]': 'Education, deep',
  'bld_capex_reno-dep-off_health[billion_EUR]': 'Health care, deep',
  'bld_capex_reno-dep-off_hotels[billion_EUR]': 'Hotels, gastronomie, deep',
  'bld_capex_reno-dep-off_offices[billion_EUR]': 'Offices, deep',
  'bld_capex_reno-dep-off_other[billion_EUR]': 'Other buildings, deep',
  'bld_capex_reno-dep-off_trade[billion_EUR]': 'Wholesale, trade, deep',
  'bld_capex_reno-dep-sfh[billion_EUR]': 'Single-family homes, deep',
  'bld_capex_reno-med-mfh[billion_EUR]': 'Multi-family homes, medium',
  'bld_capex_reno-med-off_education[billion_EUR]': 'Education, medium',
  'bld_capex_reno-med-off_health[billion_EUR]': 'Health care, medium',
  'bld_capex_reno-med-off_hotels[billion_EUR]': 'Hotels, gastronomie, medium',
  'bld_capex_reno-med-off_offices[billion_EUR]': 'Offices, medium',
  'bld_capex_reno-med-off_other[billion_EUR]': 'Other buildings, medium',
  'bld_capex_reno-med-off_trade[billion_EUR]': 'Wholesale, trade, medium',
  'bld_capex_reno-med-sfh[billion_EUR]': 'Single-family homes, deep',
  'bld_capex_reno-shl-mfh[billion_EUR]': 'Multi-family homes, shallow',
  'bld_capex_reno-shl-off_education[billion_EUR]': 'Education, shallow',
  'bld_capex_reno-shl-off_health[billion_EUR]': 'Health care, shallow',
  'bld_capex_reno-shl-off_hotels[billion_EUR]': 'Hotels, gastronomie, shallow',
  'bld_capex_reno-shl-off_offices[billion_EUR]': 'Offices, shallow',
  'bld_capex_reno-shl-off_other[billion_EUR]': 'Other buildings, shallow',
  'bld_capex_reno-shl-off_trade[billion_EUR]': 'Wholesale, trade, shallow',
  'bld_capex_reno-shl-sfh[billion_EUR]': 'Single-family homes, Shallow',
  'bld_capex_reno_dep[MEUR]': 'Deep renovation',
  'bld_capex_reno_education[MEUR]': 'Education',
  'bld_capex_reno_health[MEUR]': 'Health',
  'bld_capex_reno_hotels[MEUR]': 'Hotels',
  'bld_capex_reno_med[MEUR]': 'Medium renovation',
  'bld_capex_reno_multi-family-households[MEUR]': 'Multi-family-households',
  'bld_capex_reno_off_education[billion_EUR]': 'Education',
  'bld_capex_reno_off_health[billion_EUR]': 'Health care',
  'bld_capex_reno_off_hotels[billion_EUR]': 'Hotels, gastronomie',
  'bld_capex_reno_off_offices[billion_EUR]': 'Offices',
  'bld_capex_reno_off_other[billion_EUR]': 'Other buildings',
  'bld_capex_reno_off_trade[billion_EUR]': 'Wholesale, trade',
  'bld_capex_reno_offices[MEUR]': 'Offices',
  'bld_capex_reno_other[MEUR]': 'Other',
  'bld_capex_reno_sfh[billion_EUR]': 'Single-family homes',
  'bld_capex_reno_shl[MEUR]': 'Shallow renovation',
  'bld_capex_reno_shl[billion_EUR]': 'Shallow renovation',
  'bld_capex_reno_single-family-households[MEUR]': 'Single-family-households',
  'bld_capex_reno_trade[MEUR]': 'Trade',
  'bld_capex_tv[billion_EUR]': 'TV',
  'bld_capex_wmachine[billion_EUR]': 'Washing machine',
  'bld_elc_energy-demand_total[TWh]': 'NaN',
  'bld_elc_energy-demand_total_cost[MEUR]': 'Electricity cost (buildings)',
  'bld_emissions-CH4[Mt]': 'CH4-emisssions',
  'bld_emissions-CO2[Mt]': 'CO2-emissions',
  'bld_emissions-CO2_appliances_electricity[Mt]': 'Electricity residential appliances',
  'bld_emissions-CO2_cooking_electricity[Mt]': 'Electricity residential cooking',
  'bld_emissions-CO2_heat_electricity[Mt]': 'Electricity space heating',
  'bld_emissions-CO2_heat_non-residential_electricity[Mt]':
    'Electricity non-resdiential space heating',
  'bld_emissions-CO2_heat_residential_electricity[Mt]': 'Electricity space heating residential',
  'bld_emissions-CO2_hot-water_electricity[Mt]': 'Electricity hot water',
  'bld_emissions-CO2_lighting_electricity[Mt]': 'Electricity lighting',
  'bld_emissions-CO2_non-elec_cooking[Mt]': 'Fuels for cooking',
  'bld_emissions-CO2_non-elec_hot-water[Mt]': 'Fuels for hot water',
  'bld_emissions-CO2_non-elec_space-cooling[Mt]': 'Fuels for space cooling',
  'bld_emissions-CO2_non-residential_appliances_electricity[Mt]': 'Electricity appliances services',
  'bld_emissions-CO2_non-residential_hot-water_electricity[Mt]': 'Electricity hot water services',
  'bld_emissions-CO2_non-residential_lighting_electricity[Mt]': 'Electricity lighting services',
  'bld_emissions-CO2_non-residential_space-cooling_electricity[Mt]': 'Electricity A/C services',
  'bld_emissions-CO2_non-sh_electricity[Mt]': 'new Feb 26th 2019',
  'bld_emissions-CO2_residential_appliances_electricity[Mt]': 'Electricity residential appliances',
  'bld_emissions-CO2_residential_cooking_electricity[Mt]': 'Electricity residential cooking',
  'bld_emissions-CO2_residential_hot-water_electricity[Mt]': 'Electricity hot water homes',
  'bld_emissions-CO2_residential_lighting_electricity[Mt]': 'Electricity lighting residential',
  'bld_emissions-CO2_residential_space-cooling_electricity[Mt]': 'Electricity A/C residential',
  'bld_emissions-CO2_space-cooling_electricity[Mt]': 'Electricity space cooling',
  'bld_emissions-CO2e[Mt]': 'Buildings',
  'bld_emissions-CO2e_appliances_non-residentia[Mt]': 'Service appliances',
  'bld_emissions-CO2e_appliances_residential[Mt]': 'Residential appliances',
  'bld_emissions-CO2e_by-bld-type_education[Mt]': 'Education',
  'bld_emissions-CO2e_by-bld-type_health[Mt]': 'Health care',
  'bld_emissions-CO2e_by-bld-type_hotels[Mt]': 'Hotels, gastronomie',
  'bld_emissions-CO2e_by-bld-type_multi-family-households[Mt]': 'Multi-family homes',
  'bld_emissions-CO2e_by-bld-type_offices[Mt]': 'Offices',
  'bld_emissions-CO2e_by-bld-type_other[Mt]': 'Other buildings',
  'bld_emissions-CO2e_by-bld-type_single-family-households[Mt]': 'Single-family homes',
  'bld_emissions-CO2e_by-bld-type_trade[Mt]': 'Wholesale, trade',
  'bld_emissions-CO2e_decentral[Mt]': 'Buildings',
  'bld_emissions-CO2e_electricity[Mt]': 'new Nov 25th 2019, still working on it',
  'bld_emissions-CO2e_gas-ff-natural[Mt]': 'Natural gas',
  'bld_emissions-CO2e_heat-ambient[Mt]': 'Ambient heat',
  'bld_emissions-CO2e_heat-decentral[Mt]': 'Decentral space heating',
  'bld_emissions-CO2e_heat-geothermal[Mt]': 'Geothermal heat',
  'bld_emissions-CO2e_heat-solar[Mt]': 'Solarthermal heat',
  'bld_emissions-CO2e_liquid-ff-heatingoil[Mt]': 'Heating oil',
  'bld_emissions-CO2e_non-residential[Mt]': 'Non-residential energy',
  'bld_emissions-CO2e_non-residential_electricityMt]': 'Electricity services',
  'bld_emissions-CO2e_non-residential_heat[Mt]': 'Space heating non-residential',
  'bld_emissions-CO2e_residential[Mt]': 'Residential energy',
  'bld_emissions-CO2e_residential_electricityMt]': 'Electricity residential all uses',
  'bld_emissions-CO2e_residential_heat-decentral[Mt]': 'Residential space heating',
  'bld_emissions-CO2e_residential_heat[Mt]': 'Residential space heating',
  'bld_emissions-CO2e_solid-bio[Mt]': 'Biomass',
  'bld_emissions-CO2e_solid-ff-coal[Mt]': 'Coal',
  'bld_emissions-N2O[Mt]': 'N2O-emissions',
  'bld_energy-cost[MEUR]': 'Fossil fuel cost (Buildings)',
  'bld_energy-demand-incl-dh_fossil[TWh]': 'NaN',
  'bld_energy-demand-incl-dh_renewable[TWh]': 'NaN',
  'bld_energy-demand-space-heating-constructed_dep[GWh]': 'Highly efficient new built',
  'bld_energy-demand-space-heating-constructed_med[GWh]': 'Medium efficient new built',
  'bld_energy-demand-space-heating-constructed_shl[GWh]': 'Least efficient new built',
  'bld_energy-demand-space-heating-renovated_dep[GWh]': 'Deep renovation',
  'bld_energy-demand-space-heating-renovated_med[GWh]': 'Medium renovation',
  'bld_energy-demand-space-heating-renovated_shl[GWh]': 'Shallow renovation',
  'bld_energy-demand-space-heating-unrenovated_exi[GWh]': 'Unrenovated',
  'bld_energy-demand[TWh]': 'Buildings',
  'bld_energy-demand_appliances_electricity[TWh]': 'Electricity home appliances',
  'bld_energy-demand_constructed_dep[TWh]': 'Highly efficient new built',
  'bld_energy-demand_constructed_med[TWh]': 'Medium efficient new built',
  'bld_energy-demand_constructed_shl[TWh]': 'Least efficient new built',
  'bld_energy-demand_cooking_electricity[TWh]': 'Electricity residential cooking',
  'bld_energy-demand_cooling_heat-pump[TWh]': 'Heat-pump',
  'bld_energy-demand_gas-ff-natural[TWh]': 'NaN',
  'bld_energy-demand_heat-ambient[TWh]': 'NaN',
  'bld_energy-demand_heat-fossil[TWh]': 'Fossil energy',
  'bld_energy-demand_heat-geothermal[TWh]': '15',
  'bld_energy-demand_heat-renewable[TWh]': 'Renewable energy',
  'bld_energy-demand_heat-solar[TWh]': '17',
  'bld_energy-demand_heat[TWh]': 'heat decentral',
  'bld_energy-demand_heat_decentral_heat-renewable[TWh]': 'Ambient, solar, geothermal',
  'bld_energy-demand_heat_decentral_renewable[TWh]': 'Renewable energy carriers',
  'bld_energy-demand_heat_electricity[TWh]': 'Electricity space heat',
  'bld_energy-demand_heat_gas-bio[TWh]': 'Biogas',
  'bld_energy-demand_heat_gas-ff-natural[TWh]': 'Natural gas',
  'bld_energy-demand_heat_heat-ambient[TWh]': 'Ambient heat',
  'bld_energy-demand_heat_heat-district[TWh]': 'District heating',
  'bld_energy-demand_heat_heat-geothermal[TWh]': 'Geothermal heat',
  'bld_energy-demand_heat_heat-solar[TWh]': 'Solarthermal heat',
  'bld_energy-demand_heat_liquid-bio[TWh]': 'Liquid biofuel',
  'bld_energy-demand_heat_liquid-ff-heatingoil[TWh]': 'Heating oil',
  'bld_energy-demand_heat_non-residential_electricity[TWh]': 'NaN',
  'bld_energy-demand_heat_non-residential_electricity_cost[MEUR]': 'NaN',
  'bld_energy-demand_heat_residential_electricity[TWh]': 'NaN',
  'bld_energy-demand_heat_residential_electricity_cost[MEUR]': 'NaN',
  'bld_energy-demand_heat_solid-bio[TWh]': 'Biomass',
  'bld_energy-demand_heat_solid-ff-coal[TWh]': 'Coal',
  'bld_energy-demand_heat_solid-waste[TWh]': 'Solid waste',
  'bld_energy-demand_heating_coal[TWh]': 'Coal',
  'bld_energy-demand_heating_district-heating[TWh]': 'District-heating',
  'bld_energy-demand_heating_electricity[TWh]': 'Elec. (resistance)',
  'bld_energy-demand_heating_gas[TWh]': 'Gas',
  'bld_energy-demand_heating_heat-pump[TWh]': 'Elec. (heat-pump)',
  'bld_energy-demand_heating_heating-oil[TWh]': 'Heating-oil',
  'bld_energy-demand_heating_ambient-heat[TWh]': 'Ambient-heat',
  'bld_energy-demand_heating_other[TWh]': 'Other',
  'bld_energy-demand_heating_solar[TWh]': 'Solar-heat',
  'bld_energy-demand_heating_wood[TWh]': 'Wood',
  'bld_energy-demand_hot-water_electricity[TWh]': 'Electricity hot water',
  'bld_energy-demand_lighting_electricity[TWh]': 'Electricity lighting',
  'bld_energy-demand_liquid-ff-heatingoil[TWh]': 'NaN',
  'bld_energy-demand_non-elec_cooking[TWh]': 'Fuels for cooking',
  'bld_energy-demand_non-elec_hot-water[TWh]': 'Fuels for hot water',
  'bld_energy-demand_non-elec_space-cooling[TWh]': 'Fuels for space cooling',
  'bld_energy-demand_non-residential_appliances_electricity[TWh]': 'NaN',
  'bld_energy-demand_non-residential_appliances_electricity_cost[MEUR]': 'NaN',
  'bld_energy-demand_non-residential_education[TWh]': 'Education',
  'bld_energy-demand_non-residential_health[TWh]': 'Health care',
  'bld_energy-demand_non-residential_heat[TWh]': 'Space heating non-residential',
  'bld_energy-demand_non-residential_hot-water_electricity[TWh]': 'NaN',
  'bld_energy-demand_non-residential_hot-water_electricity_cost[MEUR]': 'NaN',
  'bld_energy-demand_non-residential_hotels[TWh]': 'Hotels, gastronomie',
  'bld_energy-demand_non-residential_offices[TWh]': 'Offices',
  'bld_energy-demand_non-residential_other[TWh]': 'Other buildings',
  'bld_energy-demand_non-residential_space-cooling_electricity[TWh]': 'NaN',
  'bld_energy-demand_non-residential_space-cooling_electricity_cost[MEUR]': 'NaN',
  'bld_energy-demand_non-residential_trade[TWh]': 'Wholesale, trade',
  'bld_energy-demand_non-sh_electricity[TWh]': 'Electricity non-space heating',
  'bld_energy-demand_non-sh_renewables[TWh]': 'Renewables',
  'bld_energy-demand_renovated_dep[TWh]': 'Deep renovation',
  'bld_energy-demand_renovated_med[TWh]': 'Medium renovation',
  'bld_energy-demand_renovated_shl[TWh]': 'Shallow renovation',
  'bld_energy-demand_residential_appliances_electricity[TWh]': 'NaN',
  'bld_energy-demand_residential_appliances_electricity_cost[MEUR]': 'NaN',
  'bld_energy-demand_residential_heat[TWh]': 'Space heating residential',
  'bld_energy-demand_residential_hot-water_electricity[TWh]': 'NaN',
  'bld_energy-demand_residential_hot-water_electricity_cost[MEUR]': 'NaN',
  'bld_energy-demand_residential_mfh[TWh]': 'Multi-family homes',
  'bld_energy-demand_residential_sfh[TWh]': 'Single-family homes',
  'bld_energy-demand_residential_space-cooling_electricity[TWh]': 'NaN',
  'bld_energy-demand_residential_space-cooling_electricity_cost[MEUR]': 'NaN',
  'bld_energy-demand_solid-bio[TWh]': 'Biomass',
  'bld_energy-demand_solid-ff-coal[TWh]': 'NaN',
  'bld_energy-demand_space-cooling_electricity[TWh]': 'Electricity space cooling',
  'bld_energy-demand_tot_electricity[TWh]': 'Electricity all energy uses',
  'bld_energy-demand_tot_gas-bio[TWh]': 'Biogas',
  'bld_energy-demand_tot_gas-ff-natural[TWh]': 'Natural gas',
  'bld_energy-demand_tot_heat-ambient[TWh]': 'Ambient heat',
  'bld_energy-demand_tot_heat-geothermal[TWh]': 'Geothermal heat',
  'bld_energy-demand_tot_heat-solar[TWh]': 'Solarthermal heat',
  'bld_energy-demand_tot_liquid-bio[TWh]': 'Biodiesel',
  'bld_energy-demand_tot_liquid-ff-heatingoil[TWh]': 'Heating oil',
  'bld_energy-demand_tot_solid-bio[TWh]': 'Biomass',
  'bld_energy-demand_tot_solid-ff-coal[TWh]': 'Coal',
  'bld_energy-demand_tot_solid-waste[TWh]': 'Solid waste',
  'bld_energy-demand_total[TWh]': 'Buildings energy demand',
  'bld_energy-demand_unrenovated_exi[TWh]': 'Unrenovated',
  'bld_energy-need_constructed_dep[TWh]': 'Highly efficient new built',
  'bld_energy-need_constructed_med[TWh]': 'Medium efficient new built',
  'bld_energy-need_constructed_shl[TWh]': 'Least efficient new built',
  'bld_energy-need_renovated_dep[TWh]': 'Deep renovation',
  'bld_energy-need_renovated_med[TWh]': 'Medium renovation',
  'bld_energy-need_renovated_shl[TWh]': 'Shallow renovation',
  'bld_energy-need_unrenovated_exi[TWh]': 'Unrenovated',
  'bld_floor-area-constructed_dep[Mm2]': 'Highly efficient new built',
  'bld_floor-area-constructed_dep[million_m2]': 'Highly efficient new built',
  'bld_floor-area-constructed_med[Mm2]': 'Medium efficient new built',
  'bld_floor-area-constructed_med[million_m2]': 'Medium efficient new built',
  'bld_floor-area-constructed_shl[Mm2]': 'Least efficient new built',
  'bld_floor-area-constructed_shl[million_m2]': 'Least efficient new built',
  'bld_floor-area-demolished-pos[million_m2]': 'Demolished existing stock',
  'bld_floor-area-demolished_dep[million_m2]': 'demolished high efficiency',
  'bld_floor-area-demolished_exi[million_m2]': 'Demolished existing stock',
  'bld_floor-area-demolished_med[million_m2]': 'Demolished medium efficiency',
  'bld_floor-area-demolished_shl[million_m2]': 'Demolished least efficiency',
  'bld_floor-area-renovated_dep[Mm2]': 'Deep renovation',
  'bld_floor-area-renovated_dep[million_m2]': 'Deep renovation',
  'bld_floor-area-renovated_med[Mm2]': 'Medium renovation',
  'bld_floor-area-renovated_med[million_m2]': 'Medium renovation',
  'bld_floor-area-renovated_shl[Mm2]': 'Shallow renovation',
  'bld_floor-area-renovated_shl[million_m2]': 'Shallow renovation',
  'bld_floor-area-unrenovated_exi[Mm2]': 'Unrenovated',
  'bld_floor-area-unrenovated_exi[million_m2]': 'Unrenovated',
  'bld_floor-area[million_m2]': 'Single-family homes',
  'bld_floor-area_education[Mm2]': 'Education',
  'bld_floor-area_health[Mm2]': 'Health',
  'bld_floor-area_hotels[Mm2]': 'Hotels',
  'bld_floor-area_multi-family-households[Mm2]': 'Multi family households',
  'bld_floor-area_new-cumulated[m2]': 'New buildings',
  'bld_floor-area_non-residential_education[million_m2]': 'Education',
  'bld_floor-area_non-residential_health[million_m2]': 'Health care',
  'bld_floor-area_non-residential_hotels[million_m2]': 'Hotels, gastronomie',
  'bld_floor-area_non-residential_offices[million_m2]': 'Offices',
  'bld_floor-area_non-residential_other[million_m2]': 'Other buildings',
  'bld_floor-area_non-residential_trade[million_m2]': 'Wholesale, trade',
  'bld_floor-area_offices[Mm2]': 'Offices',
  'bld_floor-area_other[Mm2]': 'Other uses',
  'bld_floor-area_renovated-cumulated[m2]': 'Renovated',
  'bld_floor-area_residential_mfh[million_m2]': 'Multi-family homes',
  'bld_floor-area_residential_sfh[million_m2]': 'Single-family homes',
  'bld_floor-area_single-family-households[Mm2]': 'Single family households',
  'bld_floor-area_stock_B[m2]': 'A, B',
  'bld_floor-area_stock_C[m2]': 'C',
  'bld_floor-area_stock_D[m2]': 'D',
  'bld_floor-area_stock_E[m2]': 'E',
  'bld_floor-area_stock_F[m2]': 'F, G',
  'bld_floor-area_stock_multi-family-households[m2]': 'Multi-family house',
  'bld_floor-area_stock_single-family-households[m2]': 'Single-family house',
  'bld_floor-area_trade[Mm2]': 'Trade',
  'bld_floor-area_unrenovated-cumulated[m2]': 'Unrenovated',
  'bld_fuel-cost_gas-ff-natural[MEUR]': 'Cost of natural gas for bld',
  'bld_fuel-cost_liquid-ff-oil[MEUR]': 'Cost of crude oil for bld',
  'bld_fuel-cost_solid-ff-coal[MEUR]': 'Cost of coal for bld',
  'bld_heating_B[TWh]': 'A, B',
  'bld_heating_C[TWh]': 'C',
  'bld_heating_D[TWh]': 'D',
  'bld_heating_E[TWh]': 'E',
  'bld_heating_F[TWh]': 'F, G',
  'bld_heating_coal[TWh]': 'Coal',
  'bld_heating_district-heating[TWh]': 'District-heating',
  'bld_heating_electricity[TWh]': 'Electricity',
  'bld_heating_gas[TWh]': 'Gas',
  'bld_heating_heat-pump[TWh]': 'Heat-pump',
  'bld_heating_heating-oil[TWh]': 'Heating-oil',
  'bld_heating_other[TWh]': 'Other',
  'bld_heating_solar[TWh]': 'Solar-heat',
  'bld_heating_wood[TWh]': 'Wood',
  'bld_purchase_appliances[billion_EUR]': 'Appliances',
  'bld_renovation[billion_EUR]': 'Renovation (Buildings)',
  'bld_space-heating_education[GWh]': 'Education',
  'bld_space-heating_health[GWh]': 'Health',
  'bld_space-heating_hotels[GWh]': 'Hotels',
  'bld_space-heating_multi-family-households[GWh]': 'Multi-Family-Households',
  'bld_space-heating_offices[GWh]': 'Offices',
  'bld_space-heating_other[GWh]': 'Other',
  'bld_space-heating_single-family-households[GWh]': 'Single-Family-Households',
  'bld_space-heating_trade[GWh]': 'Trade',
  'ccu_capex_depleted-oil-gas-reservoirs[MEUR]': 'Depleted oil/gas CAPEX',
  'ccu_capex_enhanced-oil-recovery[MEUR]': 'Enh. oil recovery CAPEX',
  'ccu_capex_methane-formation[MEUR]': 'Methane CAPEX',
  'ccu_capex_saline-aquifers[MEUR]': 'Saline aquifers CAPEX',
  'ccu_capex_transport[MEUR]': 'CO2 transport CAPEX',
  'ccu_capex_unmineable-coal-seams[MEUR]': 'Coal seams CAPEX',
  'ccu_ccus_ccs-potential-occupation[%]': 'CCS potential',
  'ccu_ccus_depleted-oil-gas-reservoirs[Mt]': 'Depleted oil/gas (storage)',
  'ccu_ccus_enhanced-oil-recovery[Mt]': 'Enh. oil recovery (storage)',
  'ccu_ccus_methane-formation[Mt]': 'Methane formation (usage)',
  'ccu_ccus_saline-aquifers[Mt]': 'Saline aquifers (storage)',
  'ccu_ccus_total-carbon-capture[Mt]': 'Tot. carbon capture',
  'ccu_ccus_transport[Mt]': 'CO2 transport',
  'ccu_ccus_unmineable-coal-seams[Mt]': 'Coal seams (storage)',
  'ccu_opex_transport[MEUR]': 'CO2 transport OPEX',
  'clm_drought-warning': 'NaN',
  'clm_emissions-CO2e_biogenic[Mt]': 'Biogenic CO2 captured',
  'clm_flood-warning': 'NaN',
  'clm_total_CO2e_ems[MtCO2e]': 'NaN',
  'clt_birds-max[%]': 'Birds max',
  'clt_birds-mean[%]': 'Birds mean',
  'clt_birds-min[%]': 'Birds min',
  'clt_cstlflooding-max[people]': 'Coastal Flood max',
  'clt_cstlflooding-mean[people]': 'Coastal Flood mean',
  'clt_cstlflooding-min[people]': 'Coastal Flood min',
  'clt_cum-emissions-CO2e[Mt]': 'Cum Emissions',
  'clt_drought-max[people]': 'Drought max',
  'clt_drought-mean[people]': 'Drought mean',
  'clt_drought-min[people]': 'Drought min',
  'clt_emissions-CO2e[Mt]': 'Emissions',
  'clt_flvflooding-max[people]': 'River Flood max',
  'clt_flvflooding-mean[people]': 'River Flood mean',
  'clt_flvflooding-min[people]': 'River Flood min',
  'clt_global-temp[degC]': 'Temperature anomaly',
  'clt_invertebrates-max[%]': 'Invertebrates max',
  'clt_invertebrates-mean[%]': 'Invertebrates mean',
  'clt_invertebrates-min[%]': 'Invertebrates min',
  'clt_mammals-max[%]': 'Mammals max',
  'clt_mammals-mean[%]': 'Mammals mean',
  'clt_mammals-min[%]': 'Mammals min',
  'clt_plants-max[%]': 'Plants max',
  'clt_plants-mean[%]': 'Plants mean',
  'clt_plants-min[%]': 'Plants min',
  'clt_vertebrates-max[%]': 'Vertebrates max',
  'clt_vertebrates-mean[%]': 'Vertebrates mean',
  'clt_vertebrates-min[%]': 'Vertebrates min',
  'dhg_emissions-CH4_added-district-heat[Mt]': 'CH4',
  'dhg_emissions-CO2_added-district-heat[Mt]': 'CO2',
  'dhg_emissions-CO2_heat-co-product_from-industry[Mt]': 'Waste heat',
  'dhg_emissions-CO2_heat-co-product_from-power[Mt]': 'Combined heat power',
  'dhg_emissions-CO2e-additional-heat-district[Mt]': 'District heat added',
  'dhg_emissions-CO2e_added-district-heat-fossil[Mt]': 'Fossil district heat non-CHP',
  'dhg_emissions-CO2e_added-district-heat-renewable[Mt]': 'Renewable district heat',
  'dhg_emissions-CO2e_co-product-heat[Mt]': 'Heat from CHP and industry',
  'dhg_emissions-CO2e_gas-ff-natural[Mt]': 'Natural gas',
  'dhg_emissions-CO2e_heat-ambient[Mt]': 'Heat pump',
  'dhg_emissions-CO2e_heat-district[Mt]': 'District heating',
  'dhg_emissions-CO2e_heat-geothermal[Mt]': 'Geothermal',
  'dhg_emissions-CO2e_heat-solar[Mt]': 'Solar heat',
  'dhg_emissions-CO2e_liquid-ff-heatingoil[Mt]': 'Oil',
  'dhg_emissions-CO2e_solid-bio[Mt]': 'Biomass',
  'dhg_emissions-CO2e_solid-ff-coal[Mt]': 'Coal',
  'dhg_emissions-N2O_added-district-heat[Mt]': 'N2O',
  'dhg_energy-demand_added-district-heat[TWh]': 'Additonal',
  'dhg_energy-demand_added-district-heat_fossil[TWh]': 'District heat fossil fuels',
  'dhg_energy-demand_added-district-heat_gas-ff-natural[TWh]': 'Natural gas non-CHP',
  'dhg_energy-demand_added-district-heat_heat-ambient[TWh]': 'Ambient heat',
  'dhg_energy-demand_added-district-heat_heat-geothermal[TWh]': 'Geothermal',
  'dhg_energy-demand_added-district-heat_heat-solar[TWh]': 'Solar',
  'dhg_energy-demand_added-district-heat_liquid-ff-heatingoil[TWh]': 'Oil non-CHP',
  'dhg_energy-demand_added-district-heat_renewable[TWh]': 'District heat renewables',
  'dhg_energy-demand_added-district-heat_solid-bio[TWh]': 'Biomass',
  'dhg_energy-demand_added-district-heat_solid-ff-coal[TWh]': 'Coal non-chp',
  'dhg_energy-demand_co-product-heat[TWh]': 'CHP and waste heat',
  'dhg_energy-demand_heat-co-product_from-industry[TWh]': 'Waste heat',
  'dhg_energy-demand_heat-co-product_from-power[TWh]': 'Combined heat power',
  'dhg_energy-demand_heat-district[TWh]': 'District heating',
  'elc_capacity_RES_bio_gas[GW]': 'Total bio gas capacities',
  'elc_capacity_RES_bio_mass[GW]': 'Total biomass capacities',
  'elc_capacity_RES_geothermal[GW]': 'NaN',
  'elc_capacity_RES_hydroelectric[GW]': 'NaN',
  'elc_capacity_RES_marine[GW]': 'NaN',
  'elc_capacity_RES_solar_csp[GW]': 'Total CSP capacities',
  'elc_capacity_RES_solar_pv[GW]': 'Total PV capacities',
  'elc_capacity_RES_wind_offshore[GW]': 'Total offshore wind power',
  'elc_capacity_RES_wind_onshore[GW]': 'Total onshore wind power',
  'elc_capacity_fossil_coal[GW]': 'Total coal based power plants',
  'elc_capacity_fossil_gas[GW]': 'Total gas based power plants',
  'elc_capacity_fossil_oil[GW]': 'Total oil based power plants',
  'elc_capacity_nuclear[GW]': 'Total nuclear power plants',
  'elc_capex_RES_bio_gas[MEUR]': 'biogas power',
  'elc_capex_RES_bio_mass[MEUR]': 'biomass power',
  'elc_capex_RES_other_geothermal[MEUR]': 'geothermal power',
  'elc_capex_RES_other_hydroelectric[MEUR]': 'hydropower',
  'elc_capex_RES_other_marine[MEUR]': 'marine power',
  'elc_capex_RES_solar_csp[MEUR]': 'CSP',
  'elc_capex_RES_solar_pv-rooftop[MEUR]': 'rooftop PV',
  'elc_capex_RES_solar_pv-utility[MEUR]': 'utility scale PV',
  'elc_capex_RES_wind_offshore[MEUR]': 'offshore wind power',
  'elc_capex_RES_wind_onshore[MEUR]': 'onshore wind power',
  'elc_capex_ccs[MEUR]': 'CCS',
  'elc_capex_fossil_coal[MEUR]': 'coal power',
  'elc_capex_fossil_gas[MEUR]': 'gas power',
  'elc_capex_nuclear[MEUR]': 'nuclear power',
  'elc_electricity-demand_total[TWh]': 'NaN',
  'elc_electricity-demand_total_cost[MEUR]': 'Electricity cost (power)',
  'elc_energy-cost[MEUR]': 'Energy Cost (Electricity)',
  'elc_energy-demand_gas-ff-natural[TWh]': 'Total demand for gas for electricity',
  'elc_energy-demand_liquid-ff-fuel-oil[TWh]': 'NaN',
  'elc_energy-demand_nuclear[TWh]': 'Total demand for nuclear fuel',
  'elc_energy-demand_solid-ff-coal[TWh]': 'Total demand for coal for electricity',
  'elc_energycarrier_RES_bio_gas[TWh]': 'NaN',
  'elc_energycarrier_RES_bio_mass[TWh]': 'NaN',
  'elc_energycarrier_fossil_coal[TWh]': 'NaN',
  'elc_energycarrier_fossil_gas[TWh]': 'NaN',
  'elc_energycarrier_fossil_oil[TWh]': 'NaN',
  'elc_energycarrier_nuclear[TWh]': 'NaN',
  'elc_fuel-cost_gas-bio-biogas[MEUR]': 'Cost of bio gas for electricity',
  'elc_fuel-cost_gas-ff-natural[MEUR]': 'Cost of natural gas for electricity',
  'elc_fuel-cost_liquid-ff-oil[MEUR]': 'Cost of crude oil for electricity',
  'elc_fuel-cost_solid-bio-fuelwood[MEUR]': 'Cost of biomass for electricity',
  'elc_fuel-cost_solid-ff-coal[MEUR]': 'Cost of coal for electricity',
  'elc_heat-supply-CHP_bio[TWh]': 'NaN',
  'elc_heat-supply-CHP_fossil[TWh]': 'NaN',
  'elc_investment[MEUR]': 'Investment (Electricity)',
  'elc_opex[MEUR]': 'OPEX (Electricity)',
  'elc_opex_RES_bio_gas[MEUR]': 'biogas power',
  'elc_opex_RES_bio_mass[MEUR]': 'biomass power',
  'elc_opex_RES_other_geothermal[MEUR]': 'geothermal power',
  'elc_opex_RES_other_hydroelectric[MEUR]': 'hydropower',
  'elc_opex_RES_other_marine[MEUR]': 'marine power',
  'elc_opex_RES_solar_csp[MEUR]': 'CSP',
  'elc_opex_RES_solar_pv-rooftop[MEUR]': 'rooftop PV',
  'elc_opex_RES_solar_pv-utility[MEUR]': 'utility scale PV',
  'elc_opex_RES_wind_offshore[MEUR]': 'offshore wind power',
  'elc_opex_RES_wind_onshore[MEUR]': 'onshore wind power',
  'elc_opex_fossil_coal[MEUR]': 'coal power',
  'elc_opex_fossil_gas[MEUR]': 'gas power',
  'elc_opex_nuclear[MEUR]': 'nuclear power',
  'elc_stored-CO2_gas-bio_gas[Mt]': 'Biogas-electricity',
  'elc_stored-CO2_gas-ff-natural[Mt]': 'Gas power',
  'elc_stored-CO2_liquid-ff-oil[Mt]': 'Oil power',
  'elc_stored-CO2_solid-bio_mass[Mt]': 'Biomass-electricity',
  'elc_stored-CO2_solid-ff-coal[Mt]': 'Coal power',
  'emissions-CO2e[Mt]': 'NaN',
  'emissions-CO2e_for-net-zero[Mt]': 'NaN',
  'emissions_savings_cement[Mt]': 'Cement production',
  'emissions_savings_steel[Mt]': 'Steel production',
  'emp_agriculture[%]': 'Agriculture',
  'emp_energy[%]': 'Electricity',
  'emp_industry[%]': 'Industry',
  'emp_services[%]': 'Services',
  'emp_skilled[%]': 'Tertiary education',
  'emp_total[%]': 'NaN',
  'emp_transport[%]': 'Transport',
  'emp_unskilled[%]': 'Primary and secondary education',
  'emp_wages-skilled[%]': 'Tertiary education',
  'emp_wages-unskilled[%]': 'Primary and secondary education',
  'energy_savings_cement[TWh]': 'Cement production',
  'energy_savings_steel[TWh]': 'Steel production',
  'fos_emissions-CO2e[Mt]': 'Fossil Fuels',
  'fos_energy-gap_fuel-oil[TWh]': 'NaN',
  'fos_energy-gap_gasoline[TWh]': 'NaN',
  'fos_energy-gap_kerosene[TWh]': 'NaN',
  'fos_energy-production_diesel-eq[TWh]': 'NaN',
  'fos_energy-production_fuel-oil[TWh]': 'NaN',
  'fos_energy-production_gasoline[TWh]': 'NaN',
  'fos_energy-production_kerosene[TWh]': 'NaN',
  'fos_energy_demand_diesel[TWh]': 'Total demand for diesel',
  'fos_energy_demand_fuel-oil[TWh]': 'Total demand for fuel oil',
  'fos_energy_demand_gasoline[TWh]': 'Total demand for gasoline',
  'fos_energy_demand_heatingoil[TWh]': 'Total demand for heating oil',
  'fos_energy_demand_kerosene[TWh]': 'Total demand for kerosine',
  'fos_fuel-cost_gas-ff-natural[MEUR]': 'Total cost of natural gas',
  'fos_fuel-cost_liquid-ff-oil[MEUR]': 'Total cost of crude oil',
  'fos_fuel-cost_solid-ff-coal[MEUR]': 'Total cost of coal',
  'fos_primary-demand_coal[TWh]': 'Total demand for coal',
  'fos_primary-demand_gas[TWh]': 'Total demand for natural gas',
  'fos_primary-demand_oil[TWh]': 'Total demand for crude oil',
  'h2-prod_raw-demand_gas-ff-natural[TWh]': 'NaN',
  'hydrogen_elc_demand[TWh]': 'NaN',
  'ind_CO2-emissions-CC_aluminium_prim[Mt]': 'Aluminium Primary',
  'ind_CO2-emissions-CC_aluminium_sec[Mt]': 'Aluminium Secondary',
  'ind_CO2-emissions-CC_cement_dry-kiln[Mt]': 'Cement Dry-kiln',
  'ind_CO2-emissions-CC_cement_geopolym[Mt]': 'Cement Geopolymer',
  'ind_CO2-emissions-CC_cement_wet-kiln[Mt]': 'Cement Wet-kiln',
  'ind_CO2-emissions-CC_chem_chem-tech[Mt]': 'Chemicals',
  'ind_CO2-emissions-CC_lime_lime[Mt]': 'Lime',
  'ind_CO2-emissions-CC_paper_recycled[Mt]': 'Paper Recycled',
  'ind_CO2-emissions-CC_paper_woodpulp[Mt]': 'Paper Woodpulp',
  'ind_CO2-emissions-CC_steel_BF-BOF[Mt]': 'Steel BF-BOF',
  'ind_CO2-emissions-CC_steel_hisarna[Mt]': 'Steel Hisarna',
  'ind_CO2-emissions-CC_steel_hydrog-DRI[Mt]': 'Steel Hydrogen',
  'ind_CO2-emissions-CC_steel_scrap-EAF[Mt]': 'Steel Scrap',
  'ind_elc_energy-demand_total[TWh]': 'NaN',
  'ind_elc_energy-demand_total_cost[MEUR]': 'Electricity cost (Industry)',
  'ind_emissions-CH4[Mt]': 'CH4',
  'ind_emissions-CO2[Mt]': 'CO2',
  'ind_emissions-CO2e[Mt]': 'Industry',
  'ind_emissions-CO2e_aluminium[Mt]': 'Aluminium',
  'ind_emissions-CO2e_biogenic_cement[Mt]': 'in Cement',
  'ind_emissions-CO2e_biogenic_chem[Mt]': 'in Chemicals',
  'ind_emissions-CO2e_biogenic_lime[Mt]': 'in Lime',
  'ind_emissions-CO2e_biogenic_paper[Mt]': 'in Paper',
  'ind_emissions-CO2e_biogenic_steel[Mt]': 'in Steel',
  'ind_emissions-CO2e_cement[Mt]': 'Cement',
  'ind_emissions-CO2e_chem[Mt]': 'Chemicals',
  'ind_emissions-CO2e_chemicals[Mt]': 'Chemicals',
  'ind_emissions-CO2e_copper[Mt]': 'Copper',
  'ind_emissions-CO2e_fbt[Mt]': 'Food, beverages, tobacco',
  'ind_emissions-CO2e_glass[Mt]': 'Glass',
  'ind_emissions-CO2e_lime[Mt]': 'Lime',
  'ind_emissions-CO2e_mae[Mt]': 'Machinery equip.',
  'ind_emissions-CO2e_ois[Mt]': 'Other industries',
  'ind_emissions-CO2e_paper[Mt]': 'Paper',
  'ind_emissions-CO2e_steel[Mt]': 'Steel',
  'ind_emissions-CO2e_textiles[Mt]': 'Textiles',
  'ind_emissions-CO2e_tra-equip[Mt]': 'Transport equip.',
  'ind_emissions-CO2e_wwp[Mt]': 'Wood, wood products',
  'ind_emissions-N2O[Mt]': 'N2O',
  'ind_energy-cost[MEUR]': 'Fossil fuel cost (Industry)',
  'ind_energy-demand[TWh]': 'Industry',
  'ind_energy-demand_aluminium[TWh]': 'Aluminium',
  'ind_energy-demand_aluminium_electricity[TWh]': 'Electricity',
  'ind_energy-demand_aluminium_gas-bio[TWh]': 'Gaseous Biomass',
  'ind_energy-demand_aluminium_gas-ff-natural[TWh]': 'Natural Gas',
  'ind_energy-demand_aluminium_hydrogen[TWh]': 'Hydrogen',
  'ind_energy-demand_aluminium_liquid-bio[TWh]': 'Liquid Biomass',
  'ind_energy-demand_aluminium_liquid-ff-oil[TWh]': 'Oil',
  'ind_energy-demand_aluminium_solid-bio[TWh]': 'Solid Biomass',
  'ind_energy-demand_aluminium_solid-ff-coal[TWh]': 'Coal',
  'ind_energy-demand_aluminium_solid-waste[TWh]': 'Waste',
  'ind_energy-demand_bio[TWh]': 'Biomass (industry)',
  'ind_energy-demand_cement[TWh]': 'Cement',
  'ind_energy-demand_cement_electricity[TWh]': 'Electricity',
  'ind_energy-demand_cement_gas-bio[TWh]': 'Gaseous Biomass',
  'ind_energy-demand_cement_gas-ff-natural[TWh]': 'Natural Gas',
  'ind_energy-demand_cement_hydrogen[TWh]': 'Hydrogen',
  'ind_energy-demand_cement_liquid-bio[TWh]': 'Liquid Biomass',
  'ind_energy-demand_cement_liquid-ff-oil[TWh]': 'Oil',
  'ind_energy-demand_cement_solid-bio[TWh]': 'Solid Biomass',
  'ind_energy-demand_cement_solid-ff-coal[TWh]': 'Coal',
  'ind_energy-demand_cement_solid-waste[TWh]': 'Waste',
  'ind_energy-demand_chem[TWh]': 'Chemicals',
  'ind_energy-demand_chem_electricity[TWh]': 'Electricity',
  'ind_energy-demand_chem_gas-bio[TWh]': 'Gaseous Biomass',
  'ind_energy-demand_chem_gas-ff-natural[TWh]': 'Natural Gas',
  'ind_energy-demand_chem_hydrogen[TWh]': 'Hydrogen',
  'ind_energy-demand_chem_liquid-bio[TWh]': 'Liquid Biomass',
  'ind_energy-demand_chem_liquid-ff-oil[TWh]': 'Oil',
  'ind_energy-demand_chem_solid-bio[TWh]': 'Solid Biomass',
  'ind_energy-demand_chem_solid-ff-coal[TWh]': 'Coal',
  'ind_energy-demand_chem_solid-waste[TWh]': 'Waste',
  'ind_energy-demand_chemicals[TWh]': 'Chemicals',
  'ind_energy-demand_chemicals_electricity[TWh]': 'NaN',
  'ind_energy-demand_chemicals_gas-bio[TWh]': 'NaN',
  'ind_energy-demand_chemicals_gas-ff-natural[TWh]': 'NaN',
  'ind_energy-demand_chemicals_hydrogen[TWh]': 'NaN',
  'ind_energy-demand_chemicals_liquid-bio[TWh]': 'NaN',
  'ind_energy-demand_chemicals_liquid-ff-oil[TWh]': 'NaN',
  'ind_energy-demand_chemicals_solid-bio[TWh]': 'NaN',
  'ind_energy-demand_chemicals_solid-ff-coal[TWh]': 'NaN',
  'ind_energy-demand_chemicals_solid-waste[TWh]': 'NaN',
  'ind_energy-demand_copper[TWh]': 'Copper',
  'ind_energy-demand_copper_electricity[TWh]': 'Electricity',
  'ind_energy-demand_copper_gas-bio[TWh]': 'Solid Biomass',
  'ind_energy-demand_copper_gas-ff-natural[TWh]': 'Hydrogen',
  'ind_energy-demand_copper_hydrogen[TWh]': 'Waste',
  'ind_energy-demand_copper_liquid-bio[TWh]': 'Oil',
  'ind_energy-demand_copper_liquid-ff-oil[TWh]': 'Natural Gas',
  'ind_energy-demand_copper_solid-bio[TWh]': 'Liquid Biomass',
  'ind_energy-demand_copper_solid-ff-coal[TWh]': 'Gaseous Biomass',
  'ind_energy-demand_copper_solid-waste[TWh]': 'Coal',
  'ind_energy-demand_fbt[TWh]': 'Food, beverages, tobacco',
  'ind_energy-demand_fbt_electricity[TWh]': 'Electricity',
  'ind_energy-demand_fbt_gas-bio[TWh]': 'Gaseous Biomass',
  'ind_energy-demand_fbt_gas-ff-natural[TWh]': 'Natural Gas',
  'ind_energy-demand_fbt_hydrogen[TWh]': 'Hydrogen',
  'ind_energy-demand_fbt_liquid-bio[TWh]': 'Liquid Biomass',
  'ind_energy-demand_fbt_liquid-ff-oil[TWh]': 'Oil',
  'ind_energy-demand_fbt_solid-bio[TWh]': 'Solid Biomass',
  'ind_energy-demand_fbt_solid-ff-coal[TWh]': 'Coal',
  'ind_energy-demand_fbt_solid-waste[TWh]': 'Waste',
  'ind_energy-demand_gas-ff-natural[TWh]': 'NaN',
  'ind_energy-demand_glass[TWh]': 'Glass',
  'ind_energy-demand_glass_electricity[TWh]': 'Electricity',
  'ind_energy-demand_glass_gas-bio[TWh]': 'Gaseous Biomass',
  'ind_energy-demand_glass_gas-ff-natural[TWh]': 'Natural Gas',
  'ind_energy-demand_glass_hydrogen[TWh]': 'Hydrogen',
  'ind_energy-demand_glass_liquid-bio[TWh]': 'Liquid Biomass',
  'ind_energy-demand_glass_liquid-ff-oil[TWh]': 'Oil',
  'ind_energy-demand_glass_solid-bio[TWh]': 'Solid Biomass',
  'ind_energy-demand_glass_solid-ff-coal[TWh]': 'Coal',
  'ind_energy-demand_glass_solid-waste[TWh]': 'Waste',
  'ind_energy-demand_lime[TWh]': 'Lime',
  'ind_energy-demand_lime_electricity[TWh]': 'Electricity',
  'ind_energy-demand_lime_gas-bio[TWh]': 'Gaseous Biomass',
  'ind_energy-demand_lime_gas-ff-natural[TWh]': 'Natural Gas',
  'ind_energy-demand_lime_hydrogen[TWh]': 'Hydrogen',
  'ind_energy-demand_lime_liquid-bio[TWh]': 'Liquid Biomass',
  'ind_energy-demand_lime_liquid-ff-oil[TWh]': 'Oil',
  'ind_energy-demand_lime_solid-bio[TWh]': 'Solid Biomass',
  'ind_energy-demand_lime_solid-ff-coal[TWh]': 'Coal',
  'ind_energy-demand_lime_solid-waste[TWh]': 'Waste',
  'ind_energy-demand_liquid-ff-diesel[TWh]': 'NaN',
  'ind_energy-demand_liquid-ff-fuel-oil[TWh]': 'NaN',
  'ind_energy-demand_mae[TWh]': 'Machinery equip.',
  'ind_energy-demand_mae_electricity[TWh]': 'Electricity',
  'ind_energy-demand_mae_gas-bio[TWh]': 'Gaseous Biomass',
  'ind_energy-demand_mae_gas-ff-natural[TWh]': 'Natural Gas',
  'ind_energy-demand_mae_hydrogen[TWh]': 'Hydrogen',
  'ind_energy-demand_mae_liquid-bio[TWh]': 'Liquid Biomass',
  'ind_energy-demand_mae_liquid-ff-oil[TWh]': 'Oil',
  'ind_energy-demand_mae_solid-bio[TWh]': 'Solid Biomass',
  'ind_energy-demand_mae_solid-ff-coal[TWh]': 'Coal',
  'ind_energy-demand_mae_solid-waste[TWh]': 'Waste',
  'ind_energy-demand_ois[TWh]': 'Other industries',
  'ind_energy-demand_ois_electricity[TWh]': 'Electricity',
  'ind_energy-demand_ois_gas-bio[TWh]': 'Gaseous Biomass',
  'ind_energy-demand_ois_gas-ff-natural[TWh]': 'Natural Gas',
  'ind_energy-demand_ois_hydrogen[TWh]': 'Hydrogen',
  'ind_energy-demand_ois_liquid-bio[TWh]': 'Liquid Biomass',
  'ind_energy-demand_ois_liquid-ff-oil[TWh]': 'Oil',
  'ind_energy-demand_ois_solid-bio[TWh]': 'Solid Biomass',
  'ind_energy-demand_ois_solid-ff-coal[TWh]': 'Coal',
  'ind_energy-demand_ois_solid-waste[TWh]': 'Waste',
  'ind_energy-demand_paper[TWh]': 'Paper',
  'ind_energy-demand_paper_electricity[TWh]': 'Electricity',
  'ind_energy-demand_paper_gas-bio[TWh]': 'Gaseous Biomass',
  'ind_energy-demand_paper_gas-ff-natural[TWh]': 'Natural Gas',
  'ind_energy-demand_paper_hydrogen[TWh]': 'Hydrogen',
  'ind_energy-demand_paper_liquid-bio[TWh]': 'Liquid Biomass',
  'ind_energy-demand_paper_liquid-ff-oil[TWh]': 'Oil',
  'ind_energy-demand_paper_solid-bio[TWh]': 'Solid Biomass',
  'ind_energy-demand_paper_solid-ff-coal[TWh]': 'Coal',
  'ind_energy-demand_paper_solid-waste[TWh]': 'Waste',
  'ind_energy-demand_solid-ff-coal[TWh]': 'NaN',
  'ind_energy-demand_steel[TWh]': 'Steel',
  'ind_energy-demand_steel_electricity[TWh]': 'Electricity',
  'ind_energy-demand_steel_gas-bio[TWh]': 'Gaseous Biomass',
  'ind_energy-demand_steel_gas-ff-natural[TWh]': 'Natural Gas',
  'ind_energy-demand_steel_hydrogen[TWh]': 'Hydrogen',
  'ind_energy-demand_steel_liquid-bio[TWh]': 'Liquid Biomass',
  'ind_energy-demand_steel_liquid-ff-oil[TWh]': 'Oil',
  'ind_energy-demand_steel_solid-bio[TWh]': 'Solid Biomass',
  'ind_energy-demand_steel_solid-ff-coal[TWh]': 'Coal',
  'ind_energy-demand_steel_solid-waste[TWh]': 'Waste',
  'ind_energy-demand_textiles[TWh]': 'Textiles',
  'ind_energy-demand_textiles_electricity[TWh]': 'Electricity',
  'ind_energy-demand_textiles_gas-bio[TWh]': 'Gaseous Biomass',
  'ind_energy-demand_textiles_gas-ff-natural[TWh]': 'Natural Gas',
  'ind_energy-demand_textiles_hydrogen[TWh]': 'Hydrogen',
  'ind_energy-demand_textiles_liquid-bio[TWh]': 'Liquid Biomass',
  'ind_energy-demand_textiles_liquid-ff-oil[TWh]': 'Oil',
  'ind_energy-demand_textiles_solid-bio[TWh]': 'Solid Biomass',
  'ind_energy-demand_textiles_solid-ff-coal[TWh]': 'Coal',
  'ind_energy-demand_textiles_solid-waste[TWh]': 'Waste',
  'ind_energy-demand_total[TWh]': 'Total',
  'ind_energy-demand_tra-equip[TWh]': 'Transport equip.',
  'ind_energy-demand_tra-equip_electricity[TWh]': 'Electricity',
  'ind_energy-demand_tra-equip_gas-bio[TWh]': 'Gaseous Biomass',
  'ind_energy-demand_tra-equip_gas-ff-natural[TWh]': 'Natural Gas',
  'ind_energy-demand_tra-equip_hydrogen[TWh]': 'Hydrogen',
  'ind_energy-demand_tra-equip_liquid-bio[TWh]': 'Liquid Biomass',
  'ind_energy-demand_tra-equip_liquid-ff-oil[TWh]': 'Oil',
  'ind_energy-demand_tra-equip_solid-bio[TWh]': 'Solid Biomass',
  'ind_energy-demand_tra-equip_solid-ff-coal[TWh]': 'Coal',
  'ind_energy-demand_tra-equip_solid-waste[TWh]': 'Waste',
  'ind_energy-demand_with-buildings_bio[TWh]': 'Biomass',
  'ind_energy-demand_wwp[TWh]': 'Wood, wood products',
  'ind_energy-demand_wwp_electricity[TWh]': 'Electricity',
  'ind_energy-demand_wwp_gas-bio[TWh]': 'Gaseous Biomass',
  'ind_energy-demand_wwp_gas-ff-natural[TWh]': 'Natural Gas',
  'ind_energy-demand_wwp_hydrogen[TWh]': 'Hydrogen',
  'ind_energy-demand_wwp_liquid-bio[TWh]': 'Liquid Biomass',
  'ind_energy-demand_wwp_liquid-ff-oil[TWh]': 'Oil',
  'ind_energy-demand_wwp_solid-bio[TWh]': 'Solid Biomass',
  'ind_energy-demand_wwp_solid-ff-coal[TWh]': 'Coal',
  'ind_energy-demand_wwp_solid-waste[TWh]': 'Waste',
  'ind_fuel-cost_gas-ff-natural[MEUR]': 'Cost of natural gas for ind',
  'ind_fuel-cost_liquid-ff-oil[MEUR]': 'Cost of crude oil for ind',
  'ind_fuel-cost_solid-ff-coal[MEUR]': 'Cost of coal for ind',
  'ind_investment[MEUR]': 'Investment (Industry)',
  'ind_investment_CC_amm-tech[MEUR]': 'Carbon Capture Amm.',
  'ind_investment_CC_cement[MEUR]': 'Carbon Capture Cem.',
  'ind_investment_CC_chem[MEUR]': 'Carbon Capture Chem.',
  'ind_investment_CC_paper[MEUR]': 'Carbon Capture Paper',
  'ind_investment_CC_steel[MEUR]': 'Carbon Capture Steel',
  'ind_investment_aluminium[MEUR]': 'Aluminium',
  'ind_investment_amm-tech[MEUR]': 'Ammonia',
  'ind_investment_cement[MEUR]': 'Cement',
  'ind_investment_chem[MEUR]': 'Chemicals',
  'ind_investment_glass[MEUR]': 'Glass',
  'ind_investment_lime[MEUR]': 'Lime',
  'ind_investment_paper[MEUR]': 'Paper',
  'ind_investment_steel[MEUR]': 'Steel',
  'ind_material-production_aluminium[Mt]': 'Aluminium',
  'ind_material-production_aluminium_prim[Mt]': 'Aluminium Primary',
  'ind_material-production_aluminium_sec[Mt]': 'Aluminium Secondary',
  'ind_material-production_cement[Mt]': 'Cement',
  'ind_material-production_cement_dry-kiln[Mt]': 'Cement Dry-kiln',
  'ind_material-production_cement_geopolym[Mt]': 'Cement Geopolymer',
  'ind_material-production_cement_wet-kiln[Mt]': 'Cement Wet-kiln',
  'ind_material-production_chem[Mt]': 'Chemicals',
  'ind_material-production_chem_chem-tech[Mt]': 'Chemicals',
  'ind_material-production_chemicals[Mt]': 'Chemicals',
  'ind_material-production_copper[Mt]': 'Copper',
  'ind_material-production_copper_tech[Mt]': 'Copper',
  'ind_material-production_fbt[Mt]': 'Food, beverages, tobacco',
  'ind_material-production_fbt_tech[Mt]': 'Food, beverages, tobacco',
  'ind_material-production_glass[Mt]': 'Glass',
  'ind_material-production_glass_glass[Mt]': 'Gass',
  'ind_material-production_lime[Mt]': 'Lime',
  'ind_material-production_lime_lime[Mt]': 'Lime',
  'ind_material-production_mae[Mt]': 'Machinery equip.',
  'ind_material-production_mae_tech[Mt]': 'Machinery equip.',
  'ind_material-production_ois[Mt]': 'Other industries',
  'ind_material-production_ois_tech[Mt]': 'Other industries',
  'ind_material-production_paper[Mt]': 'Paper',
  'ind_material-production_paper_recycled[Mt]': 'Paper Recycled',
  'ind_material-production_paper_woodpulp[Mt]': 'Paper Woodpulp',
  'ind_material-production_steel[Mt]': 'Steel',
  'ind_material-production_steel_BF-BOF[Mt]': 'Steel BF-BOF',
  'ind_material-production_steel_hisarna[Mt]': 'Steel Hisarna',
  'ind_material-production_steel_hydrog-DRI[Mt]': 'Steel Hydrogen',
  'ind_material-production_steel_scrap-EAF[Mt]': 'Steel Scrap',
  'ind_material-production_textiles[Mt]': 'Textiles',
  'ind_material-production_textiles_tech[Mt]': 'Textiles',
  'ind_material-production_tra-equip[Mt]': 'Transport equip.',
  'ind_material-production_tra-equip_tech[Mt]': 'Transport equip.',
  'ind_material-production_wwp[Mt]': 'Wood, wood products',
  'ind_material-production_wwp_tech[Mt]': 'Wood, wood products',
  'ind_operating-cost_CC_amm-tech[MEUR]': 'Carbon Capture Amm.',
  'ind_operating-cost_CC_cement[MEUR]': 'Carbon Capture Cem.',
  'ind_operating-cost_CC_chem[MEUR]': 'Carbon Capture Chem.',
  'ind_operating-cost_CC_paper[MEUR]': 'Carbon Capture Paper',
  'ind_operating-cost_CC_steel[MEUR]': 'Carbon Capture Steel',
  'ind_operating-cost_aluminium[MEUR]': 'Aluminium',
  'ind_operating-cost_amm-tech[MEUR]': 'Ammonia',
  'ind_operating-cost_cement[MEUR]': 'Cement',
  'ind_operating-cost_chem[MEUR]': 'Chemicals',
  'ind_operating-cost_glass[MEUR]': 'Glass',
  'ind_operating-cost_lime[MEUR]': 'Lime',
  'ind_operating-cost_paper[MEUR]': 'Paper',
  'ind_operating-cost_steel[MEUR]': 'Steel',
  'ind_opex[MEUR]': 'Operating cost (industry)',
  'lfs_appliance-own_comp[num]': 'Computer',
  'lfs_appliance-own_dishwasher[num]': 'Dishwasher',
  'lfs_appliance-own_dryer[num]': 'Dryer',
  'lfs_appliance-own_freezer[num]': 'Freezer',
  'lfs_appliance-own_fridge[num]': 'Fridge',
  'lfs_appliance-own_phone[num]': 'Smartphone',
  'lfs_appliance-own_tv[num]': 'TV',
  'lfs_appliance-own_wmachine[num]': 'Washine machine',
  'lfs_diet_afats[kcal]': 'Animal fats',
  'lfs_diet_beer[kcal]': 'Beer',
  'lfs_diet_bev-alc[kcal]': 'Alcoholic beverages',
  'lfs_diet_bev-fer[kcal]': 'NaN',
  'lfs_diet_bov[kcal]': 'NaN',
  'lfs_diet_cereals[kcal]': 'NaN',
  'lfs_diet_coffee[kcal]': 'NaN',
  'lfs_diet_dfish[kcal]': 'NaN',
  'lfs_diet_egg[kcal]': 'NaN',
  'lfs_diet_ffish[kcal]': 'NaN',
  'lfs_diet_fruits[kcal]': 'NaN',
  'lfs_diet_milk[kcal]': 'NaN',
  'lfs_diet_offal[kcal]': 'NaN',
  'lfs_diet_oilcrops[kcal]': 'NaN',
  'lfs_diet_oth-animals[kcal]': 'NaN',
  'lfs_diet_oth-aq-animals[kcal]': 'NaN',
  'lfs_diet_pfish[kcal]': 'NaN',
  'lfs_diet_pigs[kcal]': 'NaN',
  'lfs_diet_poultry[kcal]': 'NaN',
  'lfs_diet_pulses[kcal]': 'NaN',
  'lfs_diet_rice[kcal]': 'Rice',
  'lfs_diet_seafood[kcal]': 'NaN',
  'lfs_diet_sheep[kcal]': 'NaN',
  'lfs_diet_starch[kcal]': 'NaN',
  'lfs_diet_stm[kcal]': 'NaN',
  'lfs_diet_sugar[kcal]': 'NaN',
  'lfs_diet_sweet[kcal]': 'NaN',
  'lfs_diet_veg[kcal]': 'NaN',
  'lfs_diet_voil[kcal]': 'NaN',
  'lfs_diet_wine[kcal]': 'NaN',
  'lfs_energy-demand_total[TWh]': 'NaN',
  'lfs_food-wastes_beer[kcal]': 'NaN',
  'lfs_food-wastes_bev-alc[kcal]': 'NaN',
  'lfs_food-wastes_bev-fer[kcal]': 'NaN',
  'lfs_food-wastes_bov[kcal]': 'NaN',
  'lfs_food-wastes_cereals[kcal]': 'NaN',
  'lfs_food-wastes_coffee[kcal]': 'NaN',
  'lfs_food-wastes_dfish[kcal]': 'NaN',
  'lfs_food-wastes_egg[kcal]': 'NaN',
  'lfs_food-wastes_ffish[kcal]': 'NaN',
  'lfs_food-wastes_fruits[kcal]': 'NaN',
  'lfs_food-wastes_milk[kcal]': 'NaN',
  'lfs_food-wastes_offal[kcal]': 'NaN',
  'lfs_food-wastes_oilcrops[kcal]': 'NaN',
  'lfs_food-wastes_oth-animals[kcal]': 'NaN',
  'lfs_food-wastes_oth-aq-animals[kcal]': 'NaN',
  'lfs_food-wastes_pfish[kcal]': 'NaN',
  'lfs_food-wastes_pigs[kcal]': 'NaN',
  'lfs_food-wastes_poultry[kcal]': 'NaN',
  'lfs_food-wastes_pulses[kcal]': 'NaN',
  'lfs_food-wastes_seafood[kcal]': 'NaN',
  'lfs_food-wastes_sheep[kcal]': 'NaN',
  'lfs_food-wastes_starch[kcal]': 'NaN',
  'lfs_food-wastes_stm[kcal]': 'NaN',
  'lfs_food-wastes_sugar[kcal]': 'NaN',
  'lfs_food-wastes_sweet[kcal]': 'NaN',
  'lfs_food-wastes_veg[kcal]': 'NaN',
  'lfs_food-wastes_voil[kcal]': 'NaN',
  'lfs_food-wastes_wine[kcal]': 'NaN',
  'lfs_pop_population[inhabitants]': 'Population',
  'lfs_total-appliance-use_comp[h]': 'Computer',
  'lfs_total-appliance-use_phone[h]': 'Smartphone',
  'lfs_total-appliance-use_tv[h]': 'TV',
  'lus_climate-smart-forestry_biomass_csf-inc[m3]': 'NaN',
  'lus_climate-smart-forestry_biomass_csf-inc_CO2-capture[Mt]': 'NaN',
  'lus_csf_trade-balance[m3]': 'NaN',
  'lus_emissions-CO2_land-to_cropland[Mt]': 'Land converted to cropland',
  'lus_emissions-CO2_land-to_forest[Mt]': 'Land converted to forests',
  'lus_emissions-CO2_land-to_grassland[Mt]': 'Land converted to grassland',
  'lus_emissions-CO2_land-to_other[Mt]': 'Land converted to other-lands',
  'lus_emissions-CO2_land-to_settlement[Mt]': 'Land converted to settlement',
  'lus_emissions-CO2_land-to_wetland[Mt]': 'Land converted to wetland',
  'lus_emissions-CO2_land_to_cropland[Mt]': 'NaN',
  'lus_emissions-CO2_land_to_forest[Mt]': 'NaN',
  'lus_emissions-CO2_land_to_grassland[Mt]': 'NaN',
  'lus_emissions-CO2_land_to_other[Mt]': 'NaN',
  'lus_emissions-CO2_land_to_settlement[Mt]': 'NaN',
  'lus_emissions-CO2_land_to_wetland[Mt]': 'NaN',
  'lus_emissions-CO2_rem_cropland[Mt]': 'NaN',
  'lus_emissions-CO2_rem_forest[Mt]': 'NaN',
  'lus_emissions-CO2_rem_grassland[Mt]': 'NaN',
  'lus_emissions-CO2_rem_other[Mt]': 'NaN',
  'lus_emissions-CO2_rem_settlement[Mt]': 'NaN',
  'lus_emissions-CO2_rem_wetland[Mt]': 'NaN',
  'lus_emissions-CO2e[Mt]': 'Land use',
  'lus_forestry_biomass_faws_harvested[m3]': 'NaN',
  'lus_forestry_biomass_loss_burnt[m3]': 'NaN',
  'lus_fst_demand_rwe_ind-sawlog[m3]': 'Sawlogs (industry)',
  'lus_fst_demand_rwe_oth-ind-wood[m3]': 'Other industrial wood',
  'lus_fst_demand_rwe_pulp[m3]': 'Pulp wood',
  'lus_fst_demand_rwe_wood-fuel[m3]': 'Wood-fuel',
  'lus_land_cropland[ha]': 'Cropland',
  'lus_land_forest[ha]': 'Forests',
  'lus_land_grassland[ha]': 'Grassland',
  'lus_land_lulucf_agroforestry_cropland_cover-crop[MtCO2]': 'NaN',
  'lus_land_lulucf_agroforestry_cropland_cropland[MtCO2]': 'NaN',
  'lus_land_lulucf_agroforestry_cropland_hedges[MtCO2]': 'NaN',
  'lus_land_lulucf_agroforestry_cropland_no-till[MtCO2]': 'NaN',
  'lus_land_lulucf_agroforestry_grassland_grassland[MtCO2]': 'NaN',
  'lus_land_lulucf_agroforestry_grassland_hedges[MtCO2]': 'NaN',
  'lus_land_other[ha]': 'Other',
  'lus_land_protected-land[ha]': 'Protected areas',
  'lus_land_settlement[ha]': 'Settlements',
  'lus_land_shortage[ha]': 'NaN',
  'lus_land_unmanaged[ha]': 'Unmanaged',
  'lus_land_wetland[ha]': 'Wetlands',
  'lus_lulucf_emissions-CO2_afforestation[Mt]': 'NaN',
  'lus_lulucf_emissions-CO2_cropland[Mt]': 'NaN',
  'lus_lulucf_emissions-CO2_forest[Mt]': 'NaN',
  'lus_lulucf_emissions-CO2_grassland[Mt]': 'NaN',
  'lus_lulucf_emissions-CO2_other[Mt]': 'NaN',
  'lus_lulucf_emissions-CO2_settlement[Mt]': 'NaN',
  'lus_lulucf_emissions-CO2_wetland[Mt]': 'NaN',
  'min_agr_phosphate[Mt]': 'Agriculture',
  'min_agr_potash[Mt]': 'Agriculture',
  'min_bioenergy_wood[Mt]': 'Bioenergy',
  'min_building_bauxite[Mt]': 'Building',
  'min_building_copper[Mt]': 'Building',
  'min_building_iron[Mt]': 'Building',
  'min_ccus_gas[Mt]': 'CCU',
  'min_cement_sand[Mt]': 'Cement',
  'min_construction_wood[Mt]': 'Construction',
  'min_dom-appliance_bauxite[Mt]': 'Domestic Appliances',
  'min_dom-appliance_copper[Mt]': 'Domestic Appliances',
  'min_dom-appliance_iron[Mt]': 'Domestic Appliances',
  'min_electronics_bauxite[Mt]': 'Electronics',
  'min_electronics_copper[Mt]': 'Electronics',
  'min_electronics_graphite[Mt]': 'Electronics',
  'min_electronics_iron[Mt]': 'Electronics',
  'min_electronics_lead[Mt]': 'Electronics',
  'min_electronics_lithium[Mt]': 'Electronics',
  'min_electronics_manganese[Mt]': 'Electronics',
  'min_electronics_nickel[Mt]': 'Electronics',
  'min_energy_bauxite[Mt]': 'Energy',
  'min_energy_coal[Mt]': 'Coal',
  'min_energy_copper[Mt]': 'Energy',
  'min_energy_gas[Mt]': 'Extracted Gas',
  'min_energy_graphite[Mt]': 'Energy',
  'min_energy_iron[Mt]': 'Energy',
  'min_energy_lead[Mt]': 'Energy',
  'min_energy_lithium[Mt]': 'Energy',
  'min_energy_manganese[Mt]': 'Energy',
  'min_energy_nickel[Mt]': 'Energy',
  'min_energy_oil[Mt]': 'Oil',
  'min_extraction_bauxite[Mt]': 'Extraction',
  'min_extraction_copper[Mt]': 'Extraction',
  'min_extraction_graphite[Mt]': 'Extraction',
  'min_extraction_iron[Mt]': 'Extraction',
  'min_extraction_lead[Mt]': 'Extraction',
  'min_extraction_lithium[Mt]': 'Extraction',
  'min_extraction_manganese[Mt]': 'Extraction',
  'min_extraction_nickel[Mt]': 'Extraction',
  'min_extraction_phosphate[Mt]': 'Extraction',
  'min_extraction_potash[Mt]': 'Extraction',
  'min_fossil-fuel_warning': 'Warning Fossil Fuel',
  'min_glass_sand[Mt]': 'Glass',
  'min_indirect_bauxite[Mt]': 'Indirect',
  'min_indirect_copper[Mt]': 'Indirect',
  'min_indirect_graphite[Mt]': 'Indirect',
  'min_indirect_iron[Mt]': 'Indirect',
  'min_indirect_lead[Mt]': 'Indirect',
  'min_indirect_lithium[Mt]': 'Indirect',
  'min_indirect_manganese[Mt]': 'Indirect',
  'min_indirect_nickel[Mt]': 'Indirect',
  'min_industry_graphite[Mt]': 'Industry',
  'min_industry_lithium[Mt]': 'Industry',
  'min_industry_manganese[Mt]': 'Industry',
  'min_industry_nickel[Mt]': 'Industry',
  'min_infra_bauxite[Mt]': 'Infrastructure',
  'min_infra_copper[Mt]': 'Infrastructure',
  'min_infra_iron[Mt]': 'Infrastructure',
  min_mineral_warning: 'Warning Mineral',
  'min_other_bauxite[Mt]': 'Other',
  'min_other_copper[Mt]': 'Other',
  'min_other_graphite[Mt]': 'Other',
  'min_other_iron[Mt]': 'Other',
  'min_other_lead[Mt]': 'Other',
  'min_other_lithium[Mt]': 'Other',
  'min_other_manganese[Mt]': 'Other',
  'min_other_nickel[Mt]': 'Other',
  'min_other_phosphate[Mt]': 'Other',
  'min_other_potash[Mt]': 'Other',
  'min_paper_wood[Mt]': 'Paper',
  'min_relative_reserves_left_bauxite[%]': 'Bauxite',
  'min_relative_reserves_left_coal[%]': 'Coal',
  'min_relative_reserves_left_copper[%]': 'Copper',
  'min_relative_reserves_left_gas[%]': 'Gas',
  'min_relative_reserves_left_graphite[%]': 'Graphite',
  'min_relative_reserves_left_iron[%]': 'Iron',
  'min_relative_reserves_left_lead[%]': 'Lead',
  'min_relative_reserves_left_lithium[%]': 'Lithium',
  'min_relative_reserves_left_manganese[%]': 'Manganese',
  'min_relative_reserves_left_nickel[%]': 'Nickel',
  'min_relative_reserves_left_oil[%]': 'Oil',
  'min_relative_reserves_left_phosphate[%]': 'Phosphate',
  'min_relative_reserves_left_potash[%]': 'Potash',
  'min_transport_bauxite[Mt]': 'Transport',
  'min_transport_copper[Mt]': 'Transport',
  'min_transport_graphite[Mt]': 'Transport',
  'min_transport_iron[Mt]': 'Transport',
  'min_transport_lead[Mt]': 'Transport',
  'min_transport_lithium[Mt]': 'Transport',
  'min_transport_manganese[Mt]': 'Transport',
  'min_transport_nickel[Mt]': 'Transport',
  'pow_emissions-CO2e[Mt]': 'Electricity',
  'pow_emissions-CO2e_RES_bio[Mt]': 'in Electricity production',
  'pow_emissions-CO2e_fossil_coal[Mt]': 'CO2 emission of coal power',
  'pow_emissions-CO2e_fossil_gas[Mt]': 'CO2 emission of gas power',
  'pow_emissions-CO2e_fossil_oil[Mt]': 'CO2 emission of oil power',
  'pow_existing-capacity_biogas[GW]': 'Biogas power plant',
  'pow_existing-capacity_biomass[GW]': 'Biomass power plant',
  'pow_existing-capacity_coal[GW]': 'Coal-fired power plant',
  'pow_existing-capacity_gas[GW]': 'Gas-fired power plant',
  'pow_existing-capacity_geothermal[GW]': 'geothermal power',
  'pow_existing-capacity_hydroelectric[GW]': 'Hydroelectric power plant',
  'pow_existing-capacity_marine[GW]': 'marine power',
  'pow_existing-capacity_nuclear[GW]': 'Nuclear power plants',
  'pow_existing-capacity_oil[GW]': 'Oil-fired power plant',
  'pow_existing-capacity_solar-csp[GW]': 'Concentrated solar power plant',
  'pow_existing-capacity_solar-pv[GW]': 'Solar PV',
  'pow_existing-capacity_wind-offshore[GW]': 'Offshore wind farm',
  'pow_existing-capacity_wind-onshore[GW]': 'Onshore wind farm',
  'pow_gross-yearly-production_biogas[TWh]': 'NaN',
  'pow_gross-yearly-production_biomass[TWh]': 'NaN',
  'pow_gross-yearly-production_coal[TWh]': 'Electricity by coal',
  'pow_gross-yearly-production_electricity[TWh]': 'Total electricity production',
  'pow_gross-yearly-production_gas[TWh]': 'Electricity by gas',
  'pow_gross-yearly-production_geothermal[TWh]': 'Electricity by geothermal',
  'pow_gross-yearly-production_hydroelectric[TWh]': 'Electricity by hydropower',
  'pow_gross-yearly-production_marine[TWh]': 'Electricity by marine power',
  'pow_gross-yearly-production_nuclear[TWh]': 'Electricity by nuclear power',
  'pow_gross-yearly-production_oil[TWh]': 'Electricity by oil',
  'pow_gross-yearly-production_solar-csp[TWh]': 'Electricity by CSP',
  'pow_gross-yearly-production_solar-pv[TWh]': 'Electricity by PV',
  'pow_gross-yearly-production_wind-offshore[TWh]': 'Electricity by offshore wind',
  'pow_gross-yearly-production_wind-onshore[TWh]': 'Electricity by onshore wind',
  'ref_stored_CO2[Mt]': 'Oil refinery',
  'ref_total_product[TWh]': 'NaN',
  'sd_ammonium[TWh]': 'NaN',
  'sd_appliences[TWh]': 'NaN',
  'sd_bio_power[TWh]': 'NaN',
  'sd_biogas_tech_loss[TWh]': 'NaN',
  'sd_biomass_tech_loss[TWh]': 'NaN',
  'sd_building[TWh]': 'NaN',
  'sd_coal_other[TWh]': 'NaN',
  'sd_coal_tech_loss[TWh]': 'NaN',
  'sd_commercial[TWh]': 'NaN',
  'sd_cooling[TWh]': 'NaN',
  'sd_crude_oil[TWh]': 'NaN',
  'sd_gas_network[TWh]': 'NaN',
  'sd_gas_tech_loss[TWh]': 'NaN',
  'sd_heating[TWh]': 'NaN',
  'sd_hydro[TWh]': 'NaN',
  'sd_hydrogen[TWh]': 'NaN',
  'sd_industry[TWh]': 'NaN',
  'sd_nuclear_tech_loss[TWh]': 'NaN',
  'sd_oil_loss[TWh]': 'NaN',
  'sd_oil_tech_loss[TWh]': 'NaN',
  'sd_residential[TWh]': 'NaN',
  'sd_row_trading[TWh]': 'NaN',
  'sd_solar[TWh]': 'NaN',
  'sd_transport[TWh]': 'NaN',
  'sd_water_heat[TWh]': 'NaN',
  'sd_wind[TWh]': 'NaN',
  'str_CAES[TWh]': 'annual stored energy by CAES',
  'str_PHS[TWh]': 'annual stored energy by Ptx',
  'str_Ptx[TWh]': 'annual stored energy by PHS',
  'str_battery[TWh]': 'annual stored energy by batteries',
  'str_capex_CAES[MEUR]': 'CAPEX of CAES',
  'str_capex_PHS[MEUR]': 'CAPEX of PHS',
  'str_capex_Ptx[MEUR]': 'CAPEX of PtX',
  'str_capex_battery[MEUR]': 'CAPEX of battery',
  'str_capex_flywheel[MEUR]': 'CAPEX of flywheel',
  'str_daily_CAES[%]': 'CAES in daily balancing',
  'str_daily_PHS[%]': 'PHS in daily balancing',
  'str_daily_natural_gas_prod[%]': 'natural gas production in daily balancing',
  'str_flexibility_need[TWh]': 'Power system flexibility',
  'str_flywheel[TWh]': 'annual stored energy by flywheels',
  'str_natural_gas_prod[TWh]': 'natural gas production for balancing',
  'str_opex_CAES[MEUR]': 'OPEX of CAES',
  'str_opex_PHS[MEUR]': 'OPEX of PHS',
  'str_opex_Ptx[MEUR]': 'OPEX of PtX',
  'str_opex_battery[MEUR]': 'OPEX of battery',
  'str_opex_flywheel[MEUR]': 'OPEX of flywheel',
  'str_subdaily_battery[%]': 'batteries in subdaily balancing',
  'str_subdaily_flywheel[%]': 'flywheels in subdaily balancing',
  'str_subdaily_natural_gas_prod[%]': 'natural gas production in weekly balancing',
  str_warning: 'Warning electricity oversupply',
  'str_weekly_PHS[%]': 'PHS in weekly balancing',
  'str_weekly_Ptx[%]': 'Ptx in weekly balancing',
  'str_weekly_natural_gas_prod[%]': 'natural gas production in weekly balancing',
  'tra_CH4-emissions[Mt]': 'NaN',
  'tra_CO2-emissions[Mt]': 'NaN',
  'tra_N2O-emissions[Mt]': 'NaN',
  'tra_capex_2W_BEV[MEUR]': 'NaN',
  'tra_capex_2W_FCEV[MEUR]': 'NaN',
  'tra_capex_2W_ICE-diesel[MEUR]': 'NaN',
  'tra_capex_2W_ICE-gas[MEUR]': 'NaN',
  'tra_capex_2W_ICE-gasoline[MEUR]': 'NaN',
  'tra_capex_2W_PHEV[MEUR]': 'NaN',
  'tra_capex_HDVH_BEV[MEUR]': 'NaN',
  'tra_capex_HDVH_CEV[MEUR]': 'NaN',
  'tra_capex_HDVH_FCEV[MEUR]': 'NaN',
  'tra_capex_HDVH_ICE-diesel[MEUR]': 'NaN',
  'tra_capex_HDVH_ICE-gas[MEUR]': 'NaN',
  'tra_capex_HDVH_ICE-gasoline[MEUR]': 'NaN',
  'tra_capex_HDVH_PHEV-diesel[MEUR]': 'NaN',
  'tra_capex_HDVH_PHEV-gasoline[MEUR]': 'NaN',
  'tra_capex_HDVL_BEV[MEUR]': 'NaN',
  'tra_capex_HDVL_CEV[MEUR]': 'NaN',
  'tra_capex_HDVL_FCEV[MEUR]': 'NaN',
  'tra_capex_HDVL_ICE-diesel[MEUR]': 'NaN',
  'tra_capex_HDVL_ICE-gas[MEUR]': 'NaN',
  'tra_capex_HDVL_ICE-gasoline[MEUR]': 'NaN',
  'tra_capex_HDVL_PHEV-diesel[MEUR]': 'NaN',
  'tra_capex_HDVL_PHEV-gasoline[MEUR]': 'NaN',
  'tra_capex_HDVM_BEV[MEUR]': 'NaN',
  'tra_capex_HDVM_CEV[MEUR]': 'NaN',
  'tra_capex_HDVM_FCEV[MEUR]': 'NaN',
  'tra_capex_HDVM_ICE-diesel[MEUR]': 'NaN',
  'tra_capex_HDVM_ICE-gas[MEUR]': 'NaN',
  'tra_capex_HDVM_ICE-gasoline[MEUR]': 'NaN',
  'tra_capex_HDVM_PHEV-diesel[MEUR]': 'NaN',
  'tra_capex_HDVM_PHEV-gasoline[MEUR]': 'NaN',
  'tra_capex_IWW_BEV[MEUR]': 'NaN',
  'tra_capex_IWW_FCEV[MEUR]': 'NaN',
  'tra_capex_IWW_ICE[MEUR]': 'NaN',
  'tra_capex_LDV_BEV[MEUR]': 'NaN',
  'tra_capex_LDV_FCEV[MEUR]': 'NaN',
  'tra_capex_LDV_ICE-diesel[MEUR]': 'NaN',
  'tra_capex_LDV_ICE-gas[MEUR]': 'NaN',
  'tra_capex_LDV_ICE-gasoline[MEUR]': 'NaN',
  'tra_capex_LDV_PHEV-diesel[MEUR]': 'NaN',
  'tra_capex_LDV_PHEV-gasoline[MEUR]': 'NaN',
  'tra_capex_aviation_BEV[MEUR]': 'NaN',
  'tra_capex_aviation_ICE[MEUR]': 'NaN',
  'tra_capex_bus_BEV[MEUR]': 'NaN',
  'tra_capex_bus_FCEV[MEUR]': 'NaN',
  'tra_capex_bus_ICE-diesel[MEUR]': 'NaN',
  'tra_capex_bus_ICE-gas[MEUR]': 'NaN',
  'tra_capex_bus_ICE-gasoline[MEUR]': 'NaN',
  'tra_capex_bus_PHEV-diesel[MEUR]': 'NaN',
  'tra_capex_marine_BEV[MEUR]': 'NaN',
  'tra_capex_marine_FCEV[MEUR]': 'NaN',
  'tra_capex_marine_ICE[MEUR]': 'NaN',
  'tra_capex_rail[MEUR]': 'NaN',
  'tra_capex_rail_CEV[MEUR]': 'NaN',
  'tra_capex_rail_FCEV[MEUR]': 'NaN',
  'tra_capex_rail_ICE-diesel[MEUR]': 'NaN',
  'tra_capex_road[MEUR]': 'NaN',
  'tra_capex_trolley-cables[MEUR]': 'NaN',
  'tra_distance-by-car_passenger[km/person]': 'Distance by car',
  'tra_elc_energy-demand_total[TWh]': 'NaN',
  'tra_elc_energy-demand_total_cost[MEUR]': 'Electricity cost (transport)',
  'tra_elec-other[TWh]': 'NaN',
  'tra_elec-other_cost[MEUR]': 'NaN',
  'tra_elec-rail[TWh]': 'NaN',
  'tra_elec-rail_cost[MEUR]': 'NaN',
  'tra_elec-road[TWh]': 'NaN',
  'tra_elec-road_cost[MEUR]': 'NaN',
  'tra_emissions-CO2e[Mt]': 'Transport',
  'tra_emissions-CO2e_freight[Mt]': 'Freight',
  'tra_emissions-CO2e_freight_HDV[Mt]': 'Trucks',
  'tra_emissions-CO2e_freight_IWW[Mt]': 'Internal waterways',
  'tra_emissions-CO2e_freight_aviation[Mt]': 'Aviation',
  'tra_emissions-CO2e_freight_marine[Mt]': 'Marine',
  'tra_emissions-CO2e_freight_rail[Mt]': 'Rail',
  'tra_emissions-CO2e_passenger[Mt]': 'Passenger',
  'tra_emissions-CO2e_passenger_2W[Mt]': 'Two-wheelers',
  'tra_emissions-CO2e_passenger_LDV[Mt]': 'Cars',
  'tra_emissions-CO2e_passenger_aviation[Mt]': 'Aviation',
  'tra_emissions-CO2e_passenger_bus[Mt]': 'Bus',
  'tra_emissions-CO2e_passenger_rail[Mt]': 'Rail',
  'tra_energy-cost[MEUR]': 'Fossil fuel cost (Transport)',
  'tra_energy-demand[TWh]': 'Transport',
  'tra_energy-demand_biodiesel[TWh]': 'Biodiesel',
  'tra_energy-demand_bioethanol[TWh]': 'bioethanol',
  'tra_energy-demand_biogas[TWh]': 'Bionatural gas',
  'tra_energy-demand_biojetfuel[TWh]': 'Biojetfuel',
  'tra_energy-demand_diesel[TWh]': 'Diesel',
  'tra_energy-demand_electricity[TWh]': 'Electricity',
  'tra_energy-demand_gas-ff-natural[TWh]': 'NaN',
  'tra_energy-demand_gas[TWh]': 'Natural Gas',
  'tra_energy-demand_gasoline[TWh]': 'Gasoline',
  'tra_energy-demand_hydrogen[TWh]': 'Hydrogen',
  'tra_energy-demand_kerosene[TWh]': 'Kerosene',
  'tra_energy-demand_passenger[TWh]': 'Passenger',
  'tra_energy-demand_total[TWh]': 'NaN',
  'tra_freight_CH4-emissions[Mt]': 'NaN',
  'tra_freight_CO2-emissions[Mt]': 'NaN',
  'tra_freight_N2O-emissions[Mt]': 'NaN',
  'tra_freight_emissions-by-mode_CH4_HDVH[Mt]': 'NaN',
  'tra_freight_emissions-by-mode_CH4_HDVL[Mt]': 'NaN',
  'tra_freight_emissions-by-mode_CH4_HDVM[Mt]': 'NaN',
  'tra_freight_emissions-by-mode_CH4_IWW[Mt]': 'NaN',
  'tra_freight_emissions-by-mode_CH4_aviation[Mt]': 'NaN',
  'tra_freight_emissions-by-mode_CH4_marine[Mt]': 'NaN',
  'tra_freight_emissions-by-mode_CH4_rail[Mt]': 'NaN',
  'tra_freight_emissions-by-mode_N2O_HDVH[Mt]': 'NaN',
  'tra_freight_emissions-by-mode_N2O_HDVL[Mt]': 'NaN',
  'tra_freight_emissions-by-mode_N2O_HDVM[Mt]': 'NaN',
  'tra_freight_emissions-by-mode_N2O_IWW[Mt]': 'NaN',
  'tra_freight_emissions-by-mode_N2O_aviation[Mt]': 'NaN',
  'tra_freight_emissions-by-mode_N2O_marine[Mt]': 'NaN',
  'tra_freight_emissions-by-mode_N2O_rail[Mt]': 'NaN',
  'tra_freight_energy-demand-by-fuel_biodiesel[TWh]': 'Biodiesel',
  'tra_freight_energy-demand-by-fuel_bioethanol[TWh]': 'Bioethanol',
  'tra_freight_energy-demand-by-fuel_biogas[TWh]': 'Biogas',
  'tra_freight_energy-demand-by-fuel_biojetfuel[TWh]': 'Biojetfuel',
  'tra_freight_energy-demand-by-fuel_biomarinefueloil[TWh]': 'Bio marine fuel oil',
  'tra_freight_energy-demand-by-fuel_diesel[TWh]': 'Diesel',
  'tra_freight_energy-demand-by-fuel_electricity[TWh]': 'Electricity',
  'tra_freight_energy-demand-by-fuel_gas[TWh]': 'Natural Gas',
  'tra_freight_energy-demand-by-fuel_gasoline[TWh]': 'Gasoline',
  'tra_freight_energy-demand-by-fuel_hydrogen[TWh]': 'Hydrogen',
  'tra_freight_energy-demand-by-fuel_kerosene[TWh]': 'Kerosene',
  'tra_freight_energy-demand-by-fuel_marinefueloil[TWh]': 'Marine fuel oil',
  'tra_freight_energy-demand-by-mode_HDV[TWh]': 'Trucks',
  'tra_freight_energy-demand-by-mode_IWW[TWh]': 'Internal waterways',
  'tra_freight_energy-demand-by-mode_aviation[TWh]': 'Aviation',
  'tra_freight_energy-demand-by-mode_marine[TWh]': 'Marine',
  'tra_freight_energy-demand-by-mode_rail[TWh]': 'Rail',
  'tra_freight_energy-demand[TWh]': 'Freight',
  'tra_freight_modal-share_HDVH[%]': 'Heavy trucks',
  'tra_freight_modal-share_HDVL[%]': 'Light trucks',
  'tra_freight_modal-share_HDVM[%]': 'Medium trucks',
  'tra_freight_modal-share_IWW[%]': 'Internal waterways',
  'tra_freight_modal-share_aviation[%]': 'Aviation',
  'tra_freight_modal-share_bike[%]': 'Bike',
  'tra_freight_modal-share_marine[%]': 'Marine',
  'tra_freight_modal-share_rail[%]': 'Rail',
  'tra_freight_modal-share_walk[%]': 'Walk',
  'tra_freight_technology-share-fleet_HDVH_BEV[%]': 'Electric truck',
  'tra_freight_technology-share-fleet_HDVH_CEV[%]': 'Catenary Electric truck',
  'tra_freight_technology-share-fleet_HDVH_FCEV[%]': 'Fuel Cell (Hydrogen) truck',
  'tra_freight_technology-share-fleet_HDVH_ICE-diesel[%]': 'Diesel truck',
  'tra_freight_technology-share-fleet_HDVH_ICE-gas[%]': 'Gas truck',
  'tra_freight_technology-share-fleet_HDVH_ICE-gasoline[%]': 'Gasoline truck',
  'tra_freight_technology-share-fleet_HDVH_PHEV-diesel[%]': 'Plug-in Hybrid Diesel',
  'tra_freight_technology-share-fleet_HDVH_PHEV-gasoline[%]': 'Plug-in Hybrid Gasoline',
  'tra_freight_technology-share-fleet_aviation_BEV[%]': 'Electric planes',
  'tra_freight_technology-share-fleet_aviation_ICE[%]': 'Kerosene planes',
  'tra_freight_transport-demand-by-mode_HDV[tkm]': 'Trucks',
  'tra_freight_transport-demand-by-mode_IWW[tkm]': 'Internal waterways',
  'tra_freight_transport-demand-by-mode_aviation[tkm]': 'Aviation',
  'tra_freight_transport-demand-by-mode_bike[tkm]': 'Bike',
  'tra_freight_transport-demand-by-mode_marine[tkm]': 'Marine',
  'tra_freight_transport-demand-by-mode_rail[tkm]': 'Rail',
  'tra_freight_transport-demand-by-mode_walk[tkm]': 'Walk',
  'tra_freight_vehicle-fleet_HDV[number]': 'Trucks',
  'tra_freight_vehicle-fleet_IWW[number]': 'Internal waterways',
  'tra_freight_vehicle-fleet_aviation[number]': 'Aviation',
  'tra_freight_vehicle-fleet_marine[number]': 'Marine',
  'tra_freight_vehicle-fleet_rail[number]': 'Rail',
  'tra_fuel-cost_gas-ff-natural[MEUR]': 'Cost of natural gas for tra',
  'tra_fuel-cost_liquid-bio[MEUR]': 'NaN',
  'tra_fuel-cost_liquid-ff-oil[MEUR]': 'Cost of crude oil for tra',
  'tra_investment[MEUR]': 'Investment (Transport)',
  'tra_investment_bus[MEUR]': 'Bus',
  'tra_investment_households[MEUR]': 'LDVs',
  'tra_investment_infrastructure[MEUR]': 'Infrastructures',
  'tra_investment_planes[MEUR]': 'Planes',
  'tra_investment_ships[MEUR]': 'Ships',
  'tra_investment_trains[MEUR]': 'Trains',
  'tra_investment_trucks[MEUR]': 'Trucks',
  'tra_owned-cars_passenger[car/person]': 'Owned cars',
  'tra_passenger_CH4-emissions[Mt]': 'NaN',
  'tra_passenger_CO2-emissions[Mt]': 'NaN',
  'tra_passenger_N2O-emissions[Mt]': 'NaN',
  'tra_passenger_emissions-by-mode_CH4_2W[Mt]': 'NaN',
  'tra_passenger_emissions-by-mode_CH4_LDV[Mt]': 'NaN',
  'tra_passenger_emissions-by-mode_CH4_aviation[Mt]': 'NaN',
  'tra_passenger_emissions-by-mode_CH4_bus[Mt]': 'NaN',
  'tra_passenger_emissions-by-mode_CH4_rail[Mt]': 'NaN',
  'tra_passenger_emissions-by-mode_N2O_2W[Mt]': 'NaN',
  'tra_passenger_emissions-by-mode_N2O_LDV[Mt]': 'NaN',
  'tra_passenger_emissions-by-mode_N2O_aviation[Mt]': 'NaN',
  'tra_passenger_emissions-by-mode_N2O_bus[Mt]': 'NaN',
  'tra_passenger_emissions-by-mode_N2O_rail[Mt]': 'NaN',
  'tra_passenger_energy-demand-by-fuel_biodiesel[TWh]': 'Biodiesel',
  'tra_passenger_energy-demand-by-fuel_bioethanol[TWh]': 'Bioethanol',
  'tra_passenger_energy-demand-by-fuel_biogas[TWh]': 'Biogas',
  'tra_passenger_energy-demand-by-fuel_biojetfuel[TWh]': 'Biojetfuel',
  'tra_passenger_energy-demand-by-fuel_diesel[TWh]': 'Diesel',
  'tra_passenger_energy-demand-by-fuel_electricity[TWh]': 'Electricity',
  'tra_passenger_energy-demand-by-fuel_gas[TWh]': 'Natural Gas',
  'tra_passenger_energy-demand-by-fuel_gasoline[TWh]': 'Gasoline',
  'tra_passenger_energy-demand-by-fuel_hydrogen[TWh]': 'Hydrogen',
  'tra_passenger_energy-demand-by-fuel_kerosene[TWh]': 'Kerosene',
  'tra_passenger_energy-demand-by-mode_2W[TWh]': 'Two-wheelers',
  'tra_passenger_energy-demand-by-mode_LDV[TWh]': 'Cars',
  'tra_passenger_energy-demand-by-mode_aviation[TWh]': 'Aviation',
  'tra_passenger_energy-demand-by-mode_bus[TWh]': 'Bus',
  'tra_passenger_energy-demand-by-mode_metrotram[TWh]': 'Metro-Tram',
  'tra_passenger_energy-demand-by-mode_rail[TWh]': 'Rail',
  'tra_passenger_modal-share_2W[%]': 'Two-wheelers',
  'tra_passenger_modal-share_LDV[%]': 'Cars',
  'tra_passenger_modal-share_aviation[%]': 'Aviation',
  'tra_passenger_modal-share_bike[%]': 'Bike',
  'tra_passenger_modal-share_bus[%]': 'Bus',
  'tra_passenger_modal-share_metrotram[%]': 'Metro-Tram',
  'tra_passenger_modal-share_rail[%]': 'Rail',
  'tra_passenger_modal-share_walk[%]': 'Walk',
  'tra_passenger_transport-demand-by-mode_2W[pkm]': 'Two-wheelers',
  'tra_passenger_transport-demand-by-mode_LDV[pkm]': 'Cars',
  'tra_passenger_transport-demand-by-mode_aviation[pkm]': 'Aviation',
  'tra_passenger_transport-demand-by-mode_bike[pkm]': 'Bike',
  'tra_passenger_transport-demand-by-mode_bus[pkm]': 'Bus',
  'tra_passenger_transport-demand-by-mode_metrotram[pkm]': 'Metro-Tram',
  'tra_passenger_transport-demand-by-mode_rail[pkm]': 'Rail',
  'tra_passenger_transport-demand-by-mode_walk[pkm]': 'Walk',
  'tra_passenger_transport-demand-vkm_2W[vkm]': 'Two-wheelers',
  'tra_passenger_transport-demand-vkm_LDV[vkm]': 'Cars',
  'tra_passenger_transport-demand-vkm_aviation[vkm]': 'Aviation',
  'tra_passenger_transport-demand-vkm_bike[vkm]': 'Bike',
  'tra_passenger_transport-demand-vkm_bus[vkm]': 'Bus',
  'tra_passenger_transport-demand-vkm_metrotram[vkm]': 'Metro-Tram',
  'tra_passenger_transport-demand-vkm_rail[vkm]': 'Rail',
  'tra_passenger_transport-demand-vkm_walk[vkm]': 'Walk',
  'tra_passenger_vehicle-fleet_2W[number]': 'Motorbikes',
  'tra_passenger_vehicle-fleet_LDV_BEV[number]': 'Electric Cars',
  'tra_passenger_vehicle-fleet_LDV_FCEV[number]': 'Fuel Cell (Hydrogen) Cars',
  'tra_passenger_vehicle-fleet_LDV_ICE-diesel[number]': 'Diesel Cars',
  'tra_passenger_vehicle-fleet_LDV_ICE-gas[number]': 'Gas Cars',
  'tra_passenger_vehicle-fleet_LDV_ICE-gasoline[number]': 'Gasoline Cars',
  'tra_passenger_vehicle-fleet_LDV_PHEV-diesel[number]': 'Plug-in Hybrid Diesel Cars',
  'tra_passenger_vehicle-fleet_LDV_PHEV-gasoline[number]': 'Plug-in Hybrid Gasoline Cars',
  'tra_passenger_vehicle-fleet_aviation[number]': 'Planes',
  'tra_passenger_vehicle-fleet_bus[number]': 'Buses',
};

export function getPlotLabel(key: string) {
  return PLOT_LABELS[key] || key;
}
