export interface DifficultyArea {
  min: number;
  max: number;
  color: string;
  label: string;
}

export interface Lever {
  code: string;
  title: string;
  group: string;
  headline: string;
  popupText?: string;
  disabled?: boolean;
  range: (string | number)[];
  type: string;
  difficultyColors: DifficultyArea[];
}

export const sectors = [
  {
    code: 'Buildings',
    levers: [
      'lever_heatcool-behaviour',
      'lever_floor-intensity',
      'lever_appliance-own',
      'lever_appliance-use',
      'lever_building-renovation-rate',
      'lever_heating-technology-fuel',
      'lever_heating-efficiency',
      'lever_appliance-efficiency',
    ],
  },
  {
    code: 'Transport',
    levers: [
      'lever_freight_modal-share',
      'lever_freight_technology-share_new',
      'lever_freight_tkm',
      'lever_freight_utilization-rate',
      'lever_freight_vehicle-efficiency_new',
      'lever_passenger_aviation-pkm',
      'lever_passenger_modal-share',
      'lever_passenger_occupancy',
      'lever_passenger_utilization-rate',
      'lever_pkm',
      'lever_fuel-mix',
      'lever_passenger_technology-share_new',
      'lever_passenger_veh-efficiency_new',
    ],
  },
  {
    code: 'Behaviours',
    levers: [
      'lever_kcal-req',
      'lever_diet',
      'lever_fwaste',
      'lever_floor-intensity',
      'lever_heatcool-behaviour',
      'lever_appliance-own',
      'lever_appliance-use',
      'lever_paperpack',
      'lever_product-substitution-rate',
      'lever_passenger_aviation-pkm',
      'lever_passenger_modal-share',
      'lever_passenger_occupancy',
      'lever_passenger_utilization-rate',
      'lever_pkm',
    ],
  },
  { code: 'Forestry', levers: ['lever_harvest-rate'] },
  {
    code: 'Industry',
    levers: [
      'lever_paperpack',
      'lever_product-substitution-rate',
      'lever_material-efficiency',
      'lever_material-switch',
      'lever_technology-share',
      'lever_technology-development',
      'lever_energy-carrier-mix',
      'lever_lca-material-decomp',
    ],
  },
  {
    code: 'Agriculture',
    levers: [
      'lever_kcal-req',
      'lever_diet',
      'lever_fwaste',
      'lever_climate-smart-crop',
      'lever_climate-smart-livestock',
      'lever_bioenergy-capacity',
      'lever_alt-protein',
      'lever_biomass-hierarchy',
    ],
  },
  { code: 'Boundary conditions', levers: ['lever_pop', 'lever_temp'] },
];

export const levers: Lever[] = [
  {
    code: 'lever_pkm',
    title: 'Passenger distance',
    group: 'Travel',
    headline: 'Key behaviours',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_passenger_modal-share',
    title: 'Mode of transport',
    group: 'Travel',
    headline: 'Key behaviours',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_passenger_occupancy',
    title: 'Occupancy',
    group: 'Travel',
    headline: 'Key behaviours',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_passenger_utilization-rate',
    title: 'Car own or hire',
    group: 'Travel',
    headline: 'Key behaviours',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_floor-intensity',
    title: 'Living space per person',
    group: 'Homes',
    headline: 'Key behaviours',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_floor-area-fraction',
    title: 'Percentage of cooled living space',
    group: 'Homes',
    headline: 'Key behaviours',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_heatcool-behaviour',
    title: 'Space cooling & heating',
    group: 'Homes',
    headline: 'Key behaviours',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_appliance-own',
    title: 'Appliances owned',
    group: 'Homes',
    headline: 'Key behaviours',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_appliance-use',
    title: 'Appliance use',
    disabled: true,
    group: 'Homes',
    headline: 'Key behaviours',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_kcal-req',
    title: 'Calories consumed',
    group: 'Diet',
    headline: 'Key behaviours',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_diet',
    title: 'Type of diet',
    group: 'Diet',
    headline: 'Key behaviours',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_paperpack',
    title: 'Use of paper and packaging',
    group: 'Consumption',
    headline: 'Key behaviours',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_product-substitution-rate',
    title: 'Appliance retirement timing',
    group: 'Consumption',
    headline: 'Key behaviours',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_fwaste',
    title: 'Food waste',
    group: 'Consumption',
    headline: 'Key behaviours',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_freight_tkm',
    popupText:
      'Freight tonne-kilometers (tkm) represent the total transport work done to move freight. It is calculated by multiplying the weight of the freight (in tonnes) by the distance it is transported (in kilometers). Reducing freight tkm can be achieved through strategies such as optimizing logistics, improving supply chain efficiency, and promoting local sourcing to minimize transportation distances.',
    title: 'Freight distance',
    group: 'Consumption',
    headline: 'Key behaviours',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_passenger_veh-efficiency_new',
    title: 'Passenger efficiency',
    group: 'Transport',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_passenger_technology-share_new',
    title: 'Passenger technology',
    group: 'Transport',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_freight_vehicle-efficiency_new',
    popupText:
      'Freight vehicle efficiency refers to the effectiveness of freight vehicles in utilizing energy to transport goods. It is typically measured in terms of fuel consumption per ton-mile or ton-kilometer. Improving freight vehicle efficiency can involve adopting advanced technologies, optimizing vehicle design, and implementing better maintenance practices to reduce fuel consumption and emissions.',
    title: 'Freight efficiency',
    group: 'Transport',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_freight_technology-share_new',
    popupText:
      'Freight technology share refers to the proportion of freight transport that utilizes advanced or alternative technologies, such as electric or hydrogen-powered vehicles, compared to traditional fossil fuel-powered vehicles. Increasing the share of advanced technologies in freight transport can help reduce greenhouse gas emissions and improve overall energy efficiency in the logistics sector.',
    title: 'Freight technology',
    group: 'Transport',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_freight_modal-share',
    title: 'Freight mode',
    group: 'Transport',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_freight_utilization-rate',
    title: 'Freight utilization rate',
    group: 'Transport',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_fuel-mix',
    title: 'Fuel mix',
    group: 'Transport',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_building-renovation-rate',
    title: 'Building envelope',
    group: 'Buildings',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_district-heating-share',
    title: 'District heating share',
    group: 'Buildings',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_heating-technology-fuel',
    title: 'Technology and fuel share',
    group: 'Buildings',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_heating-efficiency',
    title: 'Heating and cooling efficiency',
    group: 'Buildings',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_appliance-efficiency',
    title: 'Appliances efficiency',
    group: 'Buildings',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_material-efficiency',
    title: 'Material efficiency',
    group: 'Manufacturing',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_material-switch',
    title: 'Material switch',
    group: 'Manufacturing',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_technology-share',
    title: 'Technology efficiency',
    group: 'Manufacturing',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_technology-development',
    title: 'Energy efficiency',
    group: 'Manufacturing',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_energy-carrier-mix',
    title: 'Fuel mix',
    group: 'Manufacturing',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_cc',
    title: 'Carbon Capture in manufacturing',
    group: 'Manufacturing',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_ccus',
    title: 'Carbon Capture to fuel',
    group: 'Manufacturing',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_decom_fossil',
    title: 'Decommissioning of fossil fuels',
    group: 'Power',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_ccs',
    title: 'Carbon Capture and Storage',
    group: 'Power',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_capacity_nuclear',
    title: 'Nuclear capacity',
    group: 'Power',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_capacity_RES_wind',
    title: 'Wind capacity',
    group: 'Power',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_capacity_RES_solar',
    title: 'Solar capacity',
    group: 'Power',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_capacity_RES_other',
    title: 'Other renewable capacity',
    group: 'Power',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_bal-strat',
    title: 'Balancing strategies',
    group: 'Power',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_str_charging',
    title: 'Charging profiles',
    group: 'Power',
    headline: 'Technology and fuels',
    range: ['A', 'B', 'C', 'D'],
    type: 'char',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_climate-smart-crop',
    title: 'Climate smart crop production',
    group: 'Land and food',
    headline: 'Resources and land use',
    range: ['A', 'B', 'C', 'D'],
    type: 'char',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_climate-smart-livestock',
    title: 'Climate smart livestock',
    group: 'Land and food',
    headline: 'Resources and land use',
    range: ['A', 'B', 'C', 'D'],
    type: 'char',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_bioenergy-capacity',
    title: 'Bioenergy capacity',
    group: 'Land and food',
    headline: 'Resources and land use',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_alt-protein',
    title: 'Alternative protein source',
    group: 'Land and food',
    headline: 'Resources and land use',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_climate-smart-forestry',
    title: 'Forestry practices',
    group: 'Land and food',
    headline: 'Resources and land use',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_land-man',
    title: 'Land management',
    group: 'Land and food',
    headline: 'Resources and land use',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_biomass-hierarchy',
    title: 'Hierarchy for biomass end-uses',
    group: 'Land and food',
    headline: 'Resources and land use',
    range: ['A', 'B', 'C', 'D'],
    type: 'char',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_biodiversity',
    title: 'Area set aside for nature...',
    group: 'Biodiversity',
    headline: 'Resources and land use',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_land-prioritisation',
    title: '...from agriculture or forestry',
    group: 'Biodiversity',
    headline: 'Resources and land use',
    range: ['A', 'B'],
    type: 'char',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_pop',
    title: 'Population',
    group: 'Demographics & long-term',
    headline: 'Boundary conditions',
    range: ['A', 'B', 'C', 'D'],
    type: 'char',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_urbpop',
    title: 'Urban population',
    group: 'Demographics & long-term',
    headline: 'Boundary conditions',
    range: ['A', 'B', 'C', 'D'],
    type: 'char',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_ems-after-2050',
    title: 'EU emissions after 2050',
    group: 'Demographics & long-term',
    headline: 'Boundary conditions',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_food-net-import',
    title: 'Food production',
    group: 'Domestic supply',
    headline: 'Boundary conditions',
    range: ['A', 'B', 'C', 'D'],
    type: 'char',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_product-net-import',
    title: 'Product manufacturing',
    group: 'Domestic supply',
    headline: 'Boundary conditions',
    range: ['A', 'B', 'C', 'D'],
    type: 'char',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_material-net-import',
    title: 'Material production',
    group: 'Domestic supply',
    headline: 'Boundary conditions',
    range: ['A', 'B', 'C', 'D'],
    type: 'char',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_temp',
    title: 'Global mitigation effort',
    group: 'Constraints',
    headline: 'Boundary conditions',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_passenger_aviation-pkm',
    title: 'Aviation travel',
    group: 'Travel',
    headline: 'Key behaviours',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_pv-capacity',
    title: 'Solar',
    group: 'Power',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_csp-capacity',
    title: 'Concentrated Solar Power',
    group: 'Power',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_onshore-wind-capacity',
    title: 'Wind',
    group: 'Power',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_offshore-wind-capacity',
    title: 'Offshore Wind Power',
    group: 'Power',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_biogas-capacity',
    title: 'Biogas',
    group: 'Power',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_biomass-capacity',
    title: 'Biomass',
    group: 'Power',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_hydroelectric-capacity',
    title: 'Hydro, geo & tidal',
    group: 'Power',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_geothermal-capacity',
    title: 'Geothermal',
    group: 'Power',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_marine-capacity',
    title: 'Marine',
    group: 'Power',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_gas-capacity',
    title: 'Gas',
    group: 'Power',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_oil-capacity',
    title: 'Oil',
    group: 'Power',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_coal-capacity',
    title: 'Coal',
    group: 'Power',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_nuclear-capacity',
    title: 'Nuclear',
    group: 'Power',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_carbon-storage-capacity',
    title: 'Carbon Capture ratio in power',
    group: 'Power',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_ev-charging-profile',
    title: 'EV charging habits',
    group: 'Power',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_non-residential-heat-profile',
    title: 'Non-residential heat profile',
    group: 'Power',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_residential-heat-profile',
    title: 'Residential heat profile',
    group: 'Power',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_non-residential-cooling-profile',
    title: 'Non-residential cooling profile',
    group: 'Power',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_residential-cooling-profile',
    title: 'Residential cooling profile',
    group: 'Power',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_eol-waste-management',
    title: 'Waste management',
    group: 'Manufacturing',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_eol-material-recovery',
    title: 'Material recovery',
    group: 'Manufacturing',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
  {
    code: 'lever_harvest-rate',
    title: 'Harvest rate',
    group: 'Manufacturing',
    headline: 'Technology and fuels',
    range: [1, 2, 3, 4],
    type: 'num',
    difficultyColors: [
      { min: 1, max: 1, color: '#4CAF50', label: 'Easy' },
      { min: 2, max: 2, color: '#FFC107', label: 'Moderate' },
      { min: 3, max: 3, color: '#FF9800', label: 'Hard' },
      { min: 4, max: 4, color: '#F44336', label: 'Very Hard' },
    ],
  },
];
