---
database:
  host: "localhost"
  port: "3306"
  user: "eucalc_service"
  password: "service_admin"
  schema: "levers"
  output_table: output
model:
  workspace: "/webservice/eucalc/dev"
  knime_preferences_file: /webservice/eucalc/knime_preferences.epf
  init_workflow: /webservice/eucalc/dev/_interactions/workflows/data-preprocessing-database/
  dev:
    levers_file: /webservice/eucalc/dev/_interactions/configuration/lever_position.json
    model_workflow: /webservice/eucalc/dev/_interactions/workflows/data-processing/
  prod:
    model_workflow: /webservice/eucalc/dev/_interactions/workflows/data-processing
    output_nodes:
    - 'node_0_out_1'  # Buildings
    - 'node_1249_out_1'  # Transport
    - 'node_1250_out_1'  # Industry
    - 'node_1236_out_1'  # Ammonia
    - 'node_1281_out_1'  # Electricity
    - 'node_1251_out_1'  # Agriculture
    - 'node_898_out_1'   # Land use
    - 'node_1240_out_1'  # Oil
    - 'node_1253_out_1'  # Water
    - 'node_1254_out_1'  # CCUS
    - 'node_1246_out_1'  # District Heating
    - 'node_1208_out_1'  # Minerals
    - 'node_1232_out_1'  # Climate
    - 'node_1206_out_1'  # Biodiversity
    - 'node_1257_out_1'   # Climate Emissions-
  interfaces:
    file: /webservice/eucalc/dev/_interactions/configuration/interface.xlsx
    levers_sheet: Levers
    cube_sheet: "0.2 Pathway Explorer"
  max_cache_size: 100
  scenarios:
    - [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]
    - [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2]
    - [3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2]
    - [4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,2]
log:
  suppress_run_logs: True
  level: INFO
  file: /webservice/eucalc/prod/log/api.log
api:
  port: 5000
  country_codes:
    Austria: AT
    Belgium: BE
    Bulgaria: BG
    Croatia: HR
    Cyprus: CY
    Czech Republic: CZ
    Denmark: DK
    Estonia: EE
    Finland: FI
    France: FR
    Germany: DE
    Greece: EL
    Hungary: HU
    Ireland: IE
    Italy: IT
    Latvia: LV
    Lithuania: LT
    Luxembourg: LU
    Malta: MT
    Netherlands: NL
    Poland: PL
    Portugal: PT
    Romania: RO
    Slovakia: SK
    Slovenia: SI
    Spain: ES
    Sweden: SE
    Switzerland: CH
    United Kingdom: UK
    Europe: EU
