# Define Python version (optional)
PYTHON_VERSION = 3.11.5
NAME = backend-web-rest-api
# Sync dependencies
sync:
	@echo "Syncing dependencies"
	uv sync
	uv export > requirements.txt

run:
	uv run fastapi dev src/main.py  --reload --host 0.0.0.0 --port 8000

docker-build:
	@echo "Building docker image"
	docker build -t $(NAME) .

docker-run: docker-build
	@echo "Running docker image"
	@echo "Open your browser at http://localhost:8081"
	docker run -p 8081:8081 $(NAME):latest



format:
	black src

lint:
	flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
	flake8 src --count --exit-zero --max-complexity=15 --max-line-length=127 --statistics

test:
	uv run pytest

scout:
	docker scout cves local://$(NAME):latest
