[project]
name = "backend-web-rest-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.5"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "orjson",
    "model",
]

[tool.uv.sources]
model = { path = "../model" }
