# https://github.com/EPFL-ENAC/epfl-enac-build-push-deploy-action#readme
name: deploy

"on":
  push:
    branches:
      - dev
    tags: ['v*.*.*']

jobs:
  deploy:
    permissions:
      contents: read
      packages: write
    uses: EPFL-ENAC/epfl-enac-build-push-deploy-action/.github/workflows/deploy.yml@v2.4.0
    secrets:
      token: ${{ secrets.CD_TOKEN }}
    with:
      org: epfl-leure
      repo: speed-to-zero
      build_context: '["./backend", "./frontend"]'
